In [17]:
import tensorflow as tf
import tensorflow_hub as hub
import cv2
from matplotlib import pyplot as plt
from matplotlib import animation
import numpy as np
import pandas as pd
import math
import socket
import time

# TensorFlow

In [20]:
### Optional if you are using a GPU
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)

### Load Model
model = hub.load('https://tfhub.dev/google/movenet/multipose/lightning/1')
movenet = model.signatures['serving_default']

### Load Video
video_path = '../../data/videos/'
sampleVideo = video_path + 'sampleVideo.mp4'
basicFour = video_path + 'basic_four.mp4'
basicTwo = video_path + 'basic_two.mp4'
swingDiff = video_path + 'swing_diff.mp4'
swingSame = video_path + 'swing_same.mp4'
swingRaw = video_path + 'swingRaw.mp4'
temporalDifficult = video_path + 'temporalDifficultRaw.mp4'
temporalEasy = video_path + 'temporalEasyRaw.mp4'



### Draw EDGES
EDGES = {
    (0, 1): 'm',
    (0, 2): 'c',
    (1, 3): 'm',
    (2, 4): 'c',
    (0, 5): 'm',
    (0, 6): 'c',
    (5, 7): 'm',
    (7, 9): 'm',
    (6, 8): 'c',
    (8, 10): 'c',
    (5, 6): 'y',
    (5, 11): 'm',
    (6, 12): 'c',
    (11, 12): 'y',
    (11, 13): 'm',
    (13, 15): 'm',
    (12, 14): 'c',
    (14, 16): 'c'
}

### Vector List
vectorList = [
    [0,1],
    [0,2],
    [1,3],
    [2,4],
    [3,5],
    [0,6],
    [1,7],
    [6,7],
    [6,8],
    [7,9],
    [8,10],
    [9,10]
]

# Function to loop through each person detected and render
def loop_through_people(frame, keypoints_with_scores, edges, confidence_threshold):
    for person in keypoints_with_scores:
        draw_connections(frame, person, edges, confidence_threshold)
        draw_keypoints(frame, person, confidence_threshold)


def draw_keypoints(frame, keypoints, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    for kp in shaped:
        ky, kx, kp_conf = kp
        if kp_conf > confidence_threshold:
            cv2.circle(frame, (int(kx), int(ky)), 3, (0,255,0), -1)

def draw_connections(frame, keypoints, edges, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    for edge, color in edges.items():
        p1, p2 = edge
        y1, x1, c1 = shaped[p1]
        y2, x2, c2 = shaped[p2]
        
        if (c1 > confidence_threshold) & (c2 > confidence_threshold):      
            cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0,0,255), 2)


###
# Variables for drawing plot in real-time


if __name__ == "__main__":
    ### Variables
    numberOfPeople = 6
    lamdaVal = 0.885

    minBPD = 10.0
    maxBPD = 0.0
    
    saveNum = 0
    saveBPD = []

    ### Loading Video File
    cap = cv2.VideoCapture(temporalEasy)    ### Change the File Here!!
    while cap.isOpened():
        ret, frame = cap.read()

        ### Variables for each frame
        BPD = []
        
        # Resize image
        img = frame.copy()
        img = tf.image.resize_with_pad(tf.expand_dims(img, axis=0), 384,640)
        input_img = tf.cast(img, dtype=tf.int32)
        
        # Detection section
        results = movenet(input_img)
        keypoints_with_scores = results['output_0'].numpy()[:,:,:51].reshape((6,17,3))
        keypoints_with_scores = keypoints_with_scores[:numberOfPeople]
        keypoints_only = np.delete(keypoints_with_scores,2,2)
        keypoints_only_body = np.delete(keypoints_only, [0,1,2,3,4], 1)
        
        print(keypoints_with_scores)



        # Render keypoints 
        loop_through_people(frame, keypoints_with_scores, EDGES, 0.1)
#         loop_through_people(frame, [keypoints_with_scores[0]], EDGES, 0.1)    # Check for first person.....

        
        cv2.imshow('Movenet Multipose', frame)
        
        
        if cv2.waitKey(10) & 0xFF==ord('q'):
            break
    
    cap.release()
    cv2.destroyAllWindows()

[[[0.40263897 0.91577095 0.7576814 ]
  [0.3972788  0.91948634 0.5443643 ]
  [0.39894855 0.91255    0.4900534 ]
  [0.4038157  0.9231429  0.64102554]
  [0.4057015  0.90904915 0.7117422 ]
  [0.43096387 0.93410677 0.9037962 ]
  [0.4325912  0.8989521  0.86352086]
  [0.42681193 0.9611966  0.7272117 ]
  [0.43518525 0.8760786  0.59941787]
  [0.4174626  0.9826479  0.7220818 ]
  [0.4309015  0.8540149  0.78343725]
  [0.51426613 0.9259904  0.90616983]
  [0.51202166 0.90637535 0.86833423]
  [0.57910514 0.9316432  0.88065207]
  [0.57562256 0.90221816 0.91484237]
  [0.63291943 0.9348199  0.9006905 ]
  [0.6291499  0.89738935 0.8450321 ]]

 [[0.40333614 0.08336502 0.7138668 ]
  [0.3988187  0.08646297 0.5339356 ]
  [0.3989105  0.08056959 0.59946626]
  [0.40436286 0.09064956 0.6575931 ]
  [0.40543947 0.07703294 0.6785532 ]
  [0.43197733 0.10301357 0.90192586]
  [0.43183252 0.06771537 0.88980913]
  [0.42481244 0.12988901 0.77320665]
  [0.43311775 0.04259681 0.7985779 ]
  [0.4188261  0.14612286 0.6744809 ]

[[[0.40275908 0.9155372  0.75116676]
  [0.39753887 0.9192135  0.52689373]
  [0.3986141  0.91267484 0.48156124]
  [0.4038034  0.92293024 0.65236527]
  [0.40566036 0.9090193  0.7063025 ]
  [0.43050057 0.9340994  0.9038318 ]
  [0.43238637 0.899079   0.86763513]
  [0.4261547  0.9621283  0.74372995]
  [0.43512    0.875519   0.5819787 ]
  [0.41634548 0.983537   0.7156956 ]
  [0.43089494 0.8540697  0.7858503 ]
  [0.5143863  0.925943   0.9052489 ]
  [0.51206726 0.9063439  0.8710982 ]
  [0.57919824 0.9315915  0.8770459 ]
  [0.5758403  0.9021559  0.9156878 ]
  [0.6329446  0.9348794  0.9001914 ]
  [0.62933016 0.8974004  0.8462432 ]]

 [[0.4036269  0.0830039  0.6900504 ]
  [0.39899904 0.08608758 0.5955662 ]
  [0.39921057 0.08023574 0.6372708 ]
  [0.40436003 0.09033584 0.667838  ]
  [0.40550023 0.07697828 0.6784247 ]
  [0.43193036 0.10288262 0.90197015]
  [0.43187183 0.06760789 0.8889959 ]
  [0.4249866  0.12958835 0.7814803 ]
  [0.43340605 0.04234202 0.80238086]
  [0.41882473 0.14570493 0.683698  ]

[[[0.40261084 0.91562694 0.7640685 ]
  [0.39719647 0.9193558  0.5399123 ]
  [0.39892066 0.9124242  0.47806215]
  [0.40374288 0.9229623  0.6595191 ]
  [0.40564442 0.9089312  0.7167973 ]
  [0.4303101  0.93402445 0.90494245]
  [0.4323876  0.89878017 0.8819669 ]
  [0.42585653 0.9623968  0.7499757 ]
  [0.43516248 0.87491673 0.57742244]
  [0.41616186 0.9842206  0.7087891 ]
  [0.43087447 0.8539354  0.7977459 ]
  [0.5144422  0.9260066  0.90688413]
  [0.5122975  0.90625614 0.87704647]
  [0.57919145 0.9316107  0.8777403 ]
  [0.576033   0.9020905  0.9146363 ]
  [0.63289005 0.9348655  0.90286344]
  [0.6293602  0.8973773  0.8494323 ]]

 [[0.40169364 0.2504575  0.5944823 ]
  [0.39814734 0.25360402 0.5833349 ]
  [0.39734596 0.24775703 0.6135362 ]
  [0.40497538 0.25698265 0.61403495]
  [0.40571377 0.24449824 0.6101708 ]
  [0.4293787  0.26796946 0.805589  ]
  [0.43231362 0.23385751 0.8972352 ]
  [0.4274974  0.29212233 0.68601894]
  [0.43601367 0.21307452 0.5785861 ]
  [0.42138147 0.31348464 0.69577515]

[[[0.40295053 0.91569644 0.7560113 ]
  [0.3973862  0.9193821  0.54920024]
  [0.39926684 0.91245    0.48274547]
  [0.40377682 0.9228838  0.6586918 ]
  [0.40591678 0.9088421  0.70205146]
  [0.43031764 0.93381876 0.90169936]
  [0.43258554 0.89901894 0.872476  ]
  [0.426131   0.96171486 0.7669876 ]
  [0.43538928 0.8754493  0.5813401 ]
  [0.41629896 0.9842456  0.7050118 ]
  [0.43129814 0.85358685 0.8039393 ]
  [0.51472473 0.9260166  0.90838504]
  [0.51255697 0.9063148  0.87458843]
  [0.57940894 0.9315726  0.8730393 ]
  [0.5758954  0.90211815 0.91385186]
  [0.63291633 0.9349887  0.9034167 ]
  [0.6293379  0.89739066 0.84657663]]

 [[0.40345642 0.08279454 0.68636817]
  [0.39875993 0.08588648 0.5913436 ]
  [0.3989511  0.08008044 0.63254464]
  [0.40398562 0.09019723 0.6966422 ]
  [0.40503034 0.07681169 0.70052415]
  [0.43092775 0.1027495  0.910649  ]
  [0.43044612 0.06740744 0.89837164]
  [0.4237793  0.13056728 0.7676559 ]
  [0.43284804 0.04180768 0.82982826]
  [0.41860718 0.14761154 0.64334613]

[[[0.40299696 0.9157092  0.74516004]
  [0.39756247 0.9193079  0.5464527 ]
  [0.3993139  0.91246986 0.49231395]
  [0.40400124 0.9228075  0.649357  ]
  [0.40604424 0.908912   0.69940114]
  [0.4306131  0.9337374  0.8994439 ]
  [0.43268082 0.8990728  0.8697495 ]
  [0.42649877 0.96129936 0.75186896]
  [0.4355659  0.87537825 0.59212863]
  [0.41692096 0.9829177  0.7007734 ]
  [0.4312824  0.8535515  0.80671245]
  [0.51468045 0.9260147  0.90776575]
  [0.512519   0.9062912  0.87395084]
  [0.5792844  0.9315843  0.8759798 ]
  [0.5756235  0.9022569  0.9124156 ]
  [0.6327731  0.9349618  0.90202117]
  [0.6292419  0.89737827 0.8342905 ]]

 [[0.4036417  0.08283842 0.6852812 ]
  [0.39897415 0.08593296 0.60063463]
  [0.39917165 0.08011942 0.6350602 ]
  [0.40408143 0.09018289 0.6956098 ]
  [0.40515345 0.07678956 0.693586  ]
  [0.43104273 0.10256033 0.9096037 ]
  [0.43065822 0.06734338 0.89731264]
  [0.42339727 0.1302798  0.7792767 ]
  [0.43298483 0.04200557 0.824925  ]
  [0.4186747  0.14636987 0.65032154]

[[[0.40331575 0.9158182  0.74014235]
  [0.39790377 0.91937315 0.55975395]
  [0.39960498 0.91256714 0.49963787]
  [0.4043507  0.92274714 0.63404846]
  [0.40625727 0.9088627  0.6909295 ]
  [0.43099928 0.9336347  0.9018509 ]
  [0.43276685 0.8990594  0.86931646]
  [0.42706162 0.9607248  0.7522996 ]
  [0.43555778 0.8750767  0.5927775 ]
  [0.4168937  0.98244363 0.662126  ]
  [0.43135065 0.853558   0.7975197 ]
  [0.5145362  0.9259861  0.9063313 ]
  [0.5125587  0.90630627 0.8711541 ]
  [0.5791771  0.9314976  0.87437534]
  [0.5756695  0.90243053 0.9066685 ]
  [0.6327647  0.93500006 0.9060134 ]
  [0.6290837  0.89750165 0.8377523 ]]

 [[0.40347824 0.41589624 0.7200314 ]
  [0.3987087  0.41949996 0.55468076]
  [0.39991647 0.41314617 0.5187277 ]
  [0.40570343 0.42281747 0.5561371 ]
  [0.40645552 0.40977526 0.67939425]
  [0.43088353 0.43360344 0.9077065 ]
  [0.432809   0.39949518 0.8550421 ]
  [0.4274186  0.45855132 0.7062153 ]
  [0.43495828 0.3774984  0.61093515]
  [0.42163926 0.4818835  0.70795673]

[[[0.40343624 0.91572857 0.7253262 ]
  [0.39820978 0.9193079  0.55553937]
  [0.3998015  0.9125679  0.48261455]
  [0.40465117 0.922698   0.62911934]
  [0.40635067 0.908923   0.67757004]
  [0.43094206 0.9333591  0.90004027]
  [0.43322527 0.89912874 0.8643934 ]
  [0.42711735 0.96074027 0.7447674 ]
  [0.43591934 0.8758494  0.5845874 ]
  [0.4173524  0.9815093  0.705437  ]
  [0.43073267 0.8539697  0.78444844]
  [0.5149722  0.92583716 0.90474844]
  [0.5132128  0.90622264 0.86907375]
  [0.57908076 0.93142885 0.87074065]
  [0.57602376 0.9024111  0.90706396]
  [0.6326598  0.9350193  0.9087799 ]
  [0.6291896  0.8975483  0.83811164]]

 [[0.40375552 0.08291583 0.69452363]
  [0.39916497 0.08594515 0.60007215]
  [0.39937115 0.08021256 0.6222187 ]
  [0.40434206 0.09015813 0.6609821 ]
  [0.4051885  0.07702622 0.67658126]
  [0.43115306 0.10285127 0.90980786]
  [0.43025422 0.06782199 0.8877188 ]
  [0.42405194 0.1305173  0.76756173]
  [0.43275675 0.0433518  0.8234779 ]
  [0.41869912 0.14801107 0.6767799 ]

[[[0.40382236 0.9155925  0.7063969 ]
  [0.39845294 0.9191893  0.538436  ]
  [0.39944118 0.91266865 0.49200764]
  [0.40462202 0.9228453  0.6203043 ]
  [0.40648016 0.908819   0.6679425 ]
  [0.43064636 0.9335926  0.8977648 ]
  [0.43374476 0.899213   0.857603  ]
  [0.42746362 0.96125567 0.7429902 ]
  [0.43631443 0.8770828  0.5990126 ]
  [0.41880178 0.9821063  0.7336471 ]
  [0.42944485 0.8550583  0.740827  ]
  [0.5142496  0.92609006 0.9072771 ]
  [0.51223314 0.906439   0.86454535]
  [0.5787448  0.9313599  0.87336034]
  [0.5754243  0.9025016  0.9047367 ]
  [0.63317066 0.93510073 0.90960556]
  [0.6289187  0.8974991  0.84254426]]

 [[0.4038452  0.08336058 0.6898126 ]
  [0.39934784 0.08637854 0.56489193]
  [0.39968336 0.08045069 0.5865143 ]
  [0.40476415 0.09041794 0.6228938 ]
  [0.4058841  0.07696318 0.6430692 ]
  [0.4310301  0.10308931 0.9121224 ]
  [0.4306152  0.06790026 0.8817243 ]
  [0.42431757 0.12989199 0.8020787 ]
  [0.432078   0.04375783 0.8071365 ]
  [0.41962463 0.1483855  0.7330143 ]

[[[0.403951   0.9154803  0.68056583]
  [0.39870924 0.91907454 0.5262595 ]
  [0.40015838 0.9124512  0.50830734]
  [0.40468606 0.9228881  0.6144496 ]
  [0.40618896 0.9091698  0.6839955 ]
  [0.43048167 0.9337806  0.9001953 ]
  [0.4331908  0.8995293  0.8619895 ]
  [0.4274823  0.96165955 0.74732685]
  [0.43538857 0.8765074  0.5823328 ]
  [0.41892904 0.98297167 0.72613984]
  [0.43022424 0.85472345 0.7544729 ]
  [0.514222   0.9260888  0.90659446]
  [0.5120195  0.906491   0.8605698 ]
  [0.5786154  0.9314515  0.8766189 ]
  [0.57512695 0.9024596  0.90492505]
  [0.6330883  0.93512994 0.9107126 ]
  [0.62883615 0.8975429  0.83589184]]

 [[0.4038701  0.08378956 0.6985617 ]
  [0.39938295 0.08676665 0.51236856]
  [0.399656   0.08078554 0.5332006 ]
  [0.40475792 0.09066536 0.62070113]
  [0.40611744 0.07697883 0.6429364 ]
  [0.43127656 0.1032993  0.91323227]
  [0.43070135 0.06786721 0.87745947]
  [0.42473257 0.12978928 0.79472685]
  [0.43218324 0.04343405 0.8236768 ]
  [0.41981488 0.14902382 0.7205694 ]

[[[0.40288052 0.5829177  0.6468596 ]
  [0.39876914 0.58611625 0.5502175 ]
  [0.39925486 0.5807342  0.5311336 ]
  [0.4049246  0.59029526 0.6188783 ]
  [0.4052113  0.57788    0.61924565]
  [0.42831904 0.6016506  0.85424346]
  [0.42729837 0.5675737  0.8384505 ]
  [0.40848324 0.62264746 0.71662325]
  [0.41739887 0.5467362  0.73550975]
  [0.39279115 0.63942146 0.742326  ]
  [0.3980614  0.527475   0.7838626 ]
  [0.51140225 0.59316427 0.834655  ]
  [0.50859076 0.5739249  0.86549807]
  [0.5767879  0.59755206 0.8594967 ]
  [0.57422084 0.5680916  0.8601396 ]
  [0.63325405 0.6020482  0.92586654]
  [0.62931705 0.5644952  0.9168016 ]]

 [[0.40447673 0.9158913  0.64488435]
  [0.39921457 0.9194193  0.5714078 ]
  [0.40058273 0.91282034 0.5678053 ]
  [0.4051029  0.9231133  0.5803943 ]
  [0.40644354 0.909419   0.67981577]
  [0.43084356 0.934081   0.8993875 ]
  [0.4328173  0.8998585  0.85556537]
  [0.42744774 0.96278954 0.73957276]
  [0.4344926  0.87665844 0.5973385 ]
  [0.41822994 0.98373395 0.7244865 ]

[[[0.4046498  0.915909   0.6342651 ]
  [0.3996738  0.91931623 0.56482816]
  [0.40067416 0.9128208  0.56487405]
  [0.40538913 0.9228927  0.57116705]
  [0.4064812  0.9094454  0.6822763 ]
  [0.43033478 0.93387043 0.8978757 ]
  [0.43257827 0.8999033  0.8519062 ]
  [0.42775863 0.9629421  0.7223592 ]
  [0.4338655  0.8769954  0.6185042 ]
  [0.4189174  0.98553514 0.7413879 ]
  [0.4288569  0.8544198  0.73776454]
  [0.51341164 0.9260088  0.9001168 ]
  [0.51086915 0.9062322  0.8634364 ]
  [0.57870567 0.93132114 0.8569713 ]
  [0.5742669  0.9028212  0.90790516]
  [0.6327584  0.935033   0.9135122 ]
  [0.628996   0.89755356 0.8266513 ]]

 [[0.4024397  0.25041166 0.5958555 ]
  [0.39895946 0.25363907 0.6449304 ]
  [0.39867586 0.24808596 0.58641833]
  [0.4055181  0.25725332 0.59106433]
  [0.40581417 0.2451055  0.647146  ]
  [0.43013424 0.26738685 0.82998276]
  [0.43206188 0.23421803 0.9078778 ]
  [0.42727977 0.2925415  0.75282115]
  [0.43498573 0.21272035 0.6451982 ]
  [0.42102396 0.31273568 0.76792145]

[[[0.40469906 0.9160781  0.63127595]
  [0.39977905 0.9194388  0.57618433]
  [0.4007063  0.9129478  0.56871855]
  [0.40537286 0.9228994  0.5657392 ]
  [0.40641674 0.90950215 0.68779665]
  [0.42989415 0.9337804  0.8941352 ]
  [0.43172023 0.90000325 0.8473628 ]
  [0.42802033 0.9628753  0.71818995]
  [0.4336474  0.8778802  0.633285  ]
  [0.41863704 0.98691034 0.7279486 ]
  [0.42825612 0.8541191  0.73735875]
  [0.5134082  0.92616314 0.9040408 ]
  [0.5107805  0.906297   0.8594741 ]
  [0.5792849  0.93130654 0.85283715]
  [0.57564414 0.90241003 0.9111107 ]
  [0.6329029  0.9350092  0.9135446 ]
  [0.6291801  0.8976039  0.8248941 ]]

 [[0.4025708  0.25075972 0.63441384]
  [0.3991468  0.25392053 0.64151627]
  [0.39874062 0.24840532 0.5787353 ]
  [0.40555176 0.25739425 0.5935766 ]
  [0.40582594 0.24513875 0.64502716]
  [0.43032378 0.2675178  0.83922696]
  [0.43201703 0.2342722  0.9071471 ]
  [0.42719978 0.2933161  0.7607447 ]
  [0.4344804  0.21258572 0.63813907]
  [0.42118463 0.31328985 0.7388527 ]

[[[0.40495628 0.9161665  0.61777616]
  [0.40012717 0.919539   0.5848471 ]
  [0.40093297 0.9130478  0.5670385 ]
  [0.4057901  0.92313117 0.528355  ]
  [0.40670705 0.90955824 0.67311674]
  [0.42972943 0.93378633 0.8929915 ]
  [0.43147063 0.9000025  0.8492784 ]
  [0.42781532 0.9621952  0.7152284 ]
  [0.43362784 0.87755555 0.6298158 ]
  [0.41911638 0.98432636 0.70317394]
  [0.42837852 0.85392666 0.73407835]
  [0.51379395 0.925999   0.90054685]
  [0.51097566 0.9062522  0.8631964 ]
  [0.5795088  0.9312996  0.8491267 ]
  [0.57581156 0.9024029  0.9076997 ]
  [0.6329644  0.93491787 0.91594577]
  [0.6289621  0.89758265 0.82502776]]

 [[0.40261912 0.25106177 0.6696503 ]
  [0.39923674 0.2541609  0.6301416 ]
  [0.39861605 0.24878255 0.556116  ]
  [0.40554428 0.25749308 0.59365755]
  [0.40561968 0.24526754 0.66006017]
  [0.43017864 0.2676029  0.8448218 ]
  [0.43205354 0.23428047 0.9056867 ]
  [0.42713714 0.29315874 0.7566519 ]
  [0.4348908  0.21287195 0.62431246]
  [0.42085385 0.31319717 0.7526204 ]

[[[0.40262696 0.25092584 0.65234333]
  [0.39925128 0.25407362 0.6310309 ]
  [0.39861917 0.24867749 0.5824422 ]
  [0.4054951  0.25748378 0.6004402 ]
  [0.40550816 0.24524382 0.666318  ]
  [0.42985886 0.26755574 0.8384178 ]
  [0.4316264  0.2341585  0.9042448 ]
  [0.4272985  0.29302198 0.77188164]
  [0.43482837 0.21293473 0.61756253]
  [0.4212842  0.31327733 0.775336  ]
  [0.4306636  0.18818349 0.77931285]
  [0.5139105  0.26102856 0.87076354]
  [0.5113293  0.24194649 0.9082885 ]
  [0.57788384 0.26520804 0.8779635 ]
  [0.5732911  0.23635077 0.8304148 ]
  [0.6325259  0.26825812 0.8929467 ]
  [0.6302934  0.23148601 0.8620425 ]]

 [[0.4051342  0.9162653  0.5909638 ]
  [0.40036958 0.91947836 0.5944053 ]
  [0.4011788  0.9131803  0.5873485 ]
  [0.4066763  0.92319053 0.5316361 ]
  [0.40726864 0.90977585 0.665861  ]
  [0.4303468  0.9335767  0.8914774 ]
  [0.43198    0.8999465  0.84968483]
  [0.42790842 0.9618438  0.7248258 ]
  [0.43331826 0.8763593  0.6214022 ]
  [0.42013043 0.98323816 0.6951263 ]

[[[0.4049302  0.91620964 0.61291885]
  [0.4001643  0.91945314 0.5906395 ]
  [0.4009714  0.91312236 0.5744872 ]
  [0.40662646 0.9231292  0.535166  ]
  [0.40716395 0.90962315 0.661957  ]
  [0.430443   0.93358594 0.8930379 ]
  [0.43200094 0.8997906  0.8584448 ]
  [0.4275465  0.96219605 0.71825653]
  [0.43343157 0.87604827 0.613721  ]
  [0.41974306 0.98359483 0.6920756 ]
  [0.42896172 0.8537847  0.7330301 ]
  [0.51366925 0.92609483 0.9029965 ]
  [0.5108299  0.9061843  0.8647754 ]
  [0.5796683  0.931419   0.8582319 ]
  [0.57574975 0.90239173 0.9090776 ]
  [0.6327572  0.9349883  0.9148511 ]
  [0.62910193 0.8975288  0.81741095]]

 [[0.40278882 0.25111783 0.66525406]
  [0.39943945 0.25425383 0.6299478 ]
  [0.39878398 0.24883902 0.56639475]
  [0.40586984 0.25753978 0.58573204]
  [0.40572983 0.24525456 0.6545293 ]
  [0.43007785 0.2674705  0.83920795]
  [0.43153986 0.23420568 0.9063643 ]
  [0.42703986 0.29288667 0.7680772 ]
  [0.4348414  0.21299115 0.6148476 ]
  [0.42122674 0.3133291  0.769723  ]

[[[0.4045211  0.9158222  0.6493267 ]
  [0.3995293  0.91929007 0.5564329 ]
  [0.40060088 0.9128584  0.53885096]
  [0.4057078  0.9229401  0.54722154]
  [0.40663904 0.9094659  0.68680674]
  [0.43057853 0.9338188  0.89293647]
  [0.43235278 0.89966613 0.857731  ]
  [0.4273653  0.9622671  0.7423202 ]
  [0.43386528 0.87627137 0.6050488 ]
  [0.41983432 0.9830127  0.69320947]
  [0.42950445 0.8540722  0.7373646 ]
  [0.5140106  0.92620593 0.9083743 ]
  [0.51107603 0.90634376 0.8642855 ]
  [0.5797852  0.9314537  0.8589831 ]
  [0.5758471  0.90247375 0.9091434 ]
  [0.6327797  0.9349886  0.91295946]
  [0.62906426 0.8974949  0.8129112 ]]

 [[0.4029035  0.25127938 0.675326  ]
  [0.39953765 0.25440505 0.61980623]
  [0.39886236 0.24898818 0.54744124]
  [0.40592963 0.2576009  0.58646727]
  [0.40577132 0.2453414  0.6505494 ]
  [0.43012246 0.26755112 0.8349574 ]
  [0.43142885 0.23439494 0.9073686 ]
  [0.42727122 0.29256427 0.7607796 ]
  [0.43502757 0.21338801 0.58677214]
  [0.42149192 0.313183   0.78346425]

[[[0.40409803 0.91550505 0.69185907]
  [0.39885613 0.91908836 0.5337831 ]
  [0.3995946  0.91277313 0.48723814]
  [0.40519822 0.9228635  0.5809962 ]
  [0.406502   0.90919554 0.68055934]
  [0.43062234 0.9335575  0.8967876 ]
  [0.43281278 0.89947027 0.867399  ]
  [0.42747757 0.96128285 0.752189  ]
  [0.43458542 0.8765362  0.59065765]
  [0.41969436 0.980645   0.7276648 ]
  [0.42976797 0.8542762  0.7345985 ]
  [0.5140311  0.9261565  0.90880144]
  [0.5112932  0.9063247  0.8653964 ]
  [0.57978743 0.93145984 0.85744566]
  [0.5759121  0.9024337  0.9090834 ]
  [0.63274276 0.93497753 0.9112493 ]
  [0.62911576 0.8973918  0.8155888 ]]

 [[0.40437627 0.08347776 0.6719891 ]
  [0.39999527 0.08655008 0.5314421 ]
  [0.40013504 0.08079312 0.5612531 ]
  [0.40558252 0.0905006  0.6102039 ]
  [0.40624756 0.07744546 0.62894636]
  [0.43167305 0.10230521 0.9025415 ]
  [0.43082535 0.06829568 0.8661949 ]
  [0.42640424 0.1288282  0.74613065]
  [0.4313564  0.04374567 0.81675756]
  [0.42120394 0.1473255  0.69238603]

[[[0.40366763 0.91557467 0.73389983]
  [0.39814764 0.9191     0.5457436 ]
  [0.39934433 0.9126763  0.47997227]
  [0.40467608 0.9228619  0.6045376 ]
  [0.40670782 0.9090622  0.66502756]
  [0.43061793 0.93365306 0.89361364]
  [0.43323252 0.8993797  0.86370754]
  [0.42789778 0.96141386 0.76841587]
  [0.43530473 0.87735075 0.58021045]
  [0.41991955 0.98046726 0.750432  ]
  [0.42949688 0.8550047  0.7216859 ]
  [0.5143251  0.9260464  0.9117843 ]
  [0.51190686 0.9062633  0.8767226 ]
  [0.5801755  0.9314491  0.85472697]
  [0.5768483  0.90206546 0.9132795 ]
  [0.6331162  0.93498796 0.9048679 ]
  [0.6294687  0.89725083 0.8316449 ]]

 [[0.40374216 0.08302418 0.6801939 ]
  [0.39941138 0.0861048  0.55297494]
  [0.39958307 0.080368   0.58178675]
  [0.4053151  0.09012458 0.6307251 ]
  [0.40603286 0.07714765 0.6310272 ]
  [0.4316983  0.10215052 0.90027624]
  [0.43071502 0.06795342 0.8839341 ]
  [0.42602795 0.12861049 0.7599249 ]
  [0.43141884 0.04363292 0.8110359 ]
  [0.42140466 0.14672919 0.6860893 ]

[[[0.4038692  0.9156208  0.73166597]
  [0.39849302 0.919022   0.5414323 ]
  [0.39953822 0.9127057  0.4718798 ]
  [0.4048648  0.92248935 0.61463195]
  [0.40684026 0.90886736 0.65244585]
  [0.43044192 0.9333329  0.8952024 ]
  [0.4333161  0.8991895  0.871443  ]
  [0.4279133  0.9611667  0.7615225 ]
  [0.4354368  0.8761242  0.5595017 ]
  [0.4197986  0.9811471  0.74803746]
  [0.42983052 0.85462344 0.7327904 ]
  [0.51404256 0.92597115 0.9077188 ]
  [0.5118268  0.90626585 0.8759262 ]
  [0.5801798  0.9314276  0.8559757 ]
  [0.5770943  0.90184796 0.9137574 ]
  [0.6332604  0.935018   0.9059341 ]
  [0.6295064  0.8973012  0.8303452 ]]

 [[0.4037939  0.08295884 0.67056644]
  [0.39959085 0.08606084 0.5763368 ]
  [0.3998415  0.08029606 0.57286   ]
  [0.40581578 0.08998213 0.62231016]
  [0.40634388 0.07705657 0.6082065 ]
  [0.4319793  0.10192229 0.89322203]
  [0.43077844 0.06803247 0.8815424 ]
  [0.42608875 0.12838475 0.7631587 ]
  [0.43163568 0.04379205 0.8138167 ]
  [0.4213712  0.14598404 0.69612443]

[[[0.403301   0.58240885 0.59123224]
  [0.39898926 0.58574283 0.5919827 ]
  [0.39929986 0.58059204 0.5779451 ]
  [0.40419364 0.58949965 0.6617837 ]
  [0.40381345 0.5776081  0.6658732 ]
  [0.42594612 0.599689   0.71122   ]
  [0.42505938 0.5675325  0.7728377 ]
  [0.40638423 0.6181748  0.6997083 ]
  [0.41400105 0.54824096 0.7859503 ]
  [0.38909483 0.63751405 0.72108525]
  [0.39113766 0.5293115  0.8479048 ]
  [0.509523   0.59015745 0.894046  ]
  [0.5059261  0.5723848  0.9049063 ]
  [0.5759286  0.59615517 0.8843642 ]
  [0.5736494  0.56777114 0.818742  ]
  [0.63302934 0.60178566 0.9245238 ]
  [0.6290711  0.56454843 0.8823175 ]]

 [[0.40463397 0.41589138 0.6687492 ]
  [0.39997742 0.4190487  0.5696952 ]
  [0.4003737  0.4133478  0.53020424]
  [0.40402025 0.42245585 0.6289294 ]
  [0.4046712  0.41057903 0.6838915 ]
  [0.42679584 0.43185672 0.7803056 ]
  [0.42707986 0.40039712 0.7909138 ]
  [0.40867743 0.45097598 0.76129115]
  [0.41283104 0.38527843 0.7423701 ]
  [0.38926536 0.4703887  0.67944884]

[[[0.40392697 0.9155572  0.7195092 ]
  [0.39895487 0.91889685 0.5259167 ]
  [0.3996786  0.91266537 0.4891033 ]
  [0.4053132  0.9220862  0.627649  ]
  [0.40688154 0.90858406 0.6554118 ]
  [0.4303264  0.93316805 0.897202  ]
  [0.43298835 0.8985052  0.89408416]
  [0.42763352 0.96155614 0.7494508 ]
  [0.43587714 0.8752791  0.5914737 ]
  [0.41841826 0.9833108  0.71246237]
  [0.43050367 0.85362035 0.7838733 ]
  [0.5139078  0.92594814 0.9071545 ]
  [0.5116574  0.9061028  0.8801481 ]
  [0.5796216  0.9313354  0.8583292 ]
  [0.5774561  0.90162975 0.91613185]
  [0.6328006  0.9349956  0.91312313]
  [0.6295589  0.8972692  0.83465433]]

 [[0.40467536 0.58253425 0.6068796 ]
  [0.4006703  0.58560336 0.6328108 ]
  [0.4007706  0.58011305 0.6719822 ]
  [0.40589774 0.589112   0.5993833 ]
  [0.4062268  0.57677394 0.6274113 ]
  [0.43225402 0.59885377 0.82147115]
  [0.431192   0.566964   0.8778573 ]
  [0.43761945 0.62476516 0.73311234]
  [0.4363308  0.54290557 0.6182055 ]
  [0.43759543 0.645691   0.65779465]

[[[0.40393874 0.9155437  0.71646816]
  [0.39899427 0.91893834 0.53056914]
  [0.3996746  0.9125935  0.496837  ]
  [0.4054873  0.9221929  0.6176025 ]
  [0.40699506 0.9085159  0.64187413]
  [0.43038294 0.93309736 0.8978658 ]
  [0.43329415 0.89873356 0.8851519 ]
  [0.4275518  0.9612164  0.750375  ]
  [0.43625754 0.8767988  0.5979411 ]
  [0.41880244 0.9830352  0.70223594]
  [0.42960864 0.8546953  0.7335302 ]
  [0.514362   0.92594594 0.9081622 ]
  [0.5120503  0.90609455 0.88428575]
  [0.57989335 0.93132067 0.8434735 ]
  [0.57792956 0.9014496  0.9152963 ]
  [0.63291126 0.9349999  0.9125208 ]
  [0.6297058  0.897215   0.83348995]]

 [[0.40428478 0.08326598 0.6546328 ]
  [0.39992866 0.0863044  0.56523454]
  [0.40024027 0.08042388 0.5703026 ]
  [0.40556628 0.08998334 0.6341058 ]
  [0.4065537  0.07691482 0.60181355]
  [0.4315309  0.10192347 0.8919678 ]
  [0.43050516 0.06794549 0.8755801 ]
  [0.42552835 0.12826674 0.78591174]
  [0.43210706 0.04342803 0.827097  ]
  [0.42062104 0.14668131 0.7472701 ]

[[[0.40440434 0.9156767  0.68914783]
  [0.3995399  0.9190509  0.5641002 ]
  [0.4001077  0.9127433  0.48247755]
  [0.40579182 0.92235583 0.58945876]
  [0.40706605 0.90874434 0.6289612 ]
  [0.4307185  0.9330412  0.89377415]
  [0.43349582 0.8989622  0.86730105]
  [0.42751297 0.96060276 0.7398365 ]
  [0.4365139  0.87761366 0.60537565]
  [0.42026195 0.9805104  0.7612189 ]
  [0.4298916  0.8550011  0.73318005]
  [0.5143348  0.9259023  0.9066436 ]
  [0.5120285  0.90617764 0.8780754 ]
  [0.58010626 0.93130445 0.842632  ]
  [0.57775915 0.90150416 0.9128301 ]
  [0.6328008  0.9349875  0.905987  ]
  [0.6297725  0.8972384  0.82889247]]

 [[0.40483698 0.41517782 0.62408173]
  [0.40059906 0.41832146 0.55702394]
  [0.40068144 0.4126351  0.5814201 ]
  [0.40645707 0.4219534  0.6050031 ]
  [0.4068641  0.4090487  0.65397984]
  [0.43180487 0.43105283 0.8478467 ]
  [0.4336503  0.39954555 0.82979137]
  [0.4324615  0.45614392 0.79268277]
  [0.43722674 0.3765673  0.57880306]
  [0.43136665 0.48253223 0.68084514]

[[[0.40534848 0.41523552 0.6079506 ]
  [0.40117893 0.41836056 0.5346585 ]
  [0.40108436 0.41266766 0.5993017 ]
  [0.40707967 0.4220464  0.622953  ]
  [0.40743822 0.4090348  0.67009354]
  [0.4324474  0.4308025  0.8384841 ]
  [0.43433827 0.39942893 0.83908564]
  [0.4346549  0.45460525 0.71940374]
  [0.43742535 0.37573683 0.561341  ]
  [0.4344718  0.48212573 0.68210775]
  [0.43318188 0.35483462 0.7558442 ]
  [0.51289755 0.425083   0.8732091 ]
  [0.5117728  0.40618    0.8656839 ]
  [0.5770544  0.43028697 0.7755082 ]
  [0.5761529  0.40071097 0.91326106]
  [0.63378733 0.43546566 0.8891108 ]
  [0.62865806 0.39780778 0.8361121 ]]

 [[0.40412423 0.91569275 0.70938104]
  [0.39929372 0.91908616 0.57983136]
  [0.3998596  0.9127814  0.4702275 ]
  [0.4058637  0.92240304 0.5831848 ]
  [0.4069932  0.9088254  0.6338237 ]
  [0.43101716 0.9330086  0.89568704]
  [0.4333564  0.8989788  0.8681119 ]
  [0.42776394 0.9605507  0.7449504 ]
  [0.43610483 0.8764314  0.6081859 ]
  [0.42031235 0.9802236  0.7642564 ]

[[[0.4054658  0.41550007 0.6131086 ]
  [0.40110123 0.41886854 0.55446166]
  [0.40118057 0.4128573  0.5718096 ]
  [0.4072047  0.42236528 0.6173162 ]
  [0.40750477 0.40917903 0.6689554 ]
  [0.4325177  0.43110895 0.85798746]
  [0.43438825 0.39963296 0.83235365]
  [0.43484706 0.45456472 0.72157615]
  [0.43784627 0.3771152  0.53980803]
  [0.43436348 0.48222062 0.6952661 ]
  [0.43329948 0.35559645 0.77035385]
  [0.5133388  0.42521283 0.87796736]
  [0.51193213 0.4062643  0.865165  ]
  [0.57723343 0.4304485  0.7682277 ]
  [0.5766527  0.4006582  0.9128374 ]
  [0.6337226  0.4355184  0.8879958 ]
  [0.62865144 0.39772007 0.8381044 ]]

 [[0.40410063 0.91562045 0.69576794]
  [0.39923036 0.91913766 0.5790561 ]
  [0.39977917 0.9127304  0.47537202]
  [0.4058096  0.9225833  0.58544976]
  [0.4069484  0.9089028  0.64784884]
  [0.43084282 0.93323946 0.8948119 ]
  [0.4331896  0.8988902  0.87507445]
  [0.4279883  0.9608097  0.7489925 ]
  [0.43628177 0.8759762  0.61829174]
  [0.42007792 0.9807397  0.7612857 ]

[[[0.40537518 0.41556078 0.6136198 ]
  [0.4008863  0.4189209  0.5612186 ]
  [0.40117654 0.41284847 0.56651807]
  [0.40711576 0.42247787 0.60586   ]
  [0.40764374 0.4091994  0.67727894]
  [0.43283078 0.43149754 0.8708516 ]
  [0.4347771  0.39970517 0.82734334]
  [0.43469048 0.45467123 0.7143316 ]
  [0.43796587 0.37616938 0.53526306]
  [0.43414134 0.4824309  0.6872618 ]
  [0.4335638  0.35522223 0.76229393]
  [0.5135581  0.42533278 0.88345265]
  [0.51195204 0.4063129  0.86260253]
  [0.5776031  0.4306684  0.76838404]
  [0.5763172  0.4010848  0.9096877 ]
  [0.6338217  0.43550047 0.8851642 ]
  [0.62874824 0.39774784 0.82954097]]

 [[0.40390962 0.08317642 0.6720756 ]
  [0.39972663 0.08615212 0.56710976]
  [0.40004417 0.08033822 0.5768826 ]
  [0.4056816  0.09005333 0.6374283 ]
  [0.40654716 0.07686993 0.6049429 ]
  [0.43173873 0.10170094 0.88804275]
  [0.43074986 0.06793701 0.873129  ]
  [0.42570302 0.12768172 0.7552874 ]
  [0.4328713  0.04377198 0.80719656]
  [0.4214513  0.14478807 0.70226216]

[[[0.40447113 0.41550538 0.63883764]
  [0.40006602 0.4190216  0.5649193 ]
  [0.40071282 0.41284552 0.5538744 ]
  [0.40676677 0.4225746  0.58597517]
  [0.40698057 0.40927544 0.649146  ]
  [0.4330867  0.43154272 0.8615242 ]
  [0.43449435 0.39978442 0.835842  ]
  [0.43482387 0.45508385 0.72792375]
  [0.43781123 0.37690687 0.52848506]
  [0.43410832 0.48240623 0.69113934]
  [0.4333553  0.35566548 0.7784796 ]
  [0.51324725 0.42540404 0.882409  ]
  [0.5118101  0.40629098 0.86193687]
  [0.5784615  0.4307634  0.7753861 ]
  [0.576226   0.40085268 0.90736264]
  [0.63425964 0.4356044  0.8801119 ]
  [0.62849545 0.39779994 0.8253954 ]]

 [[0.40440235 0.91536754 0.6652388 ]
  [0.39977515 0.91896915 0.5710041 ]
  [0.40005895 0.9125617  0.54107183]
  [0.40637326 0.92253906 0.5589913 ]
  [0.40701768 0.9089659  0.6405087 ]
  [0.43105397 0.9331231  0.8967601 ]
  [0.43263158 0.8990167  0.88116837]
  [0.4279661  0.9606148  0.741476  ]
  [0.43563065 0.8748097  0.61196643]
  [0.42062935 0.97994393 0.77088714]

[[[0.4043711  0.4153715  0.6467034 ]
  [0.39999983 0.41889092 0.5563895 ]
  [0.4003056  0.4127253  0.55605525]
  [0.40672776 0.42246485 0.58458835]
  [0.40685612 0.40928465 0.6514861 ]
  [0.43309307 0.4315477  0.8603921 ]
  [0.4338733  0.39976835 0.8399826 ]
  [0.43496558 0.45530015 0.7332434 ]
  [0.43750963 0.3763196  0.583581  ]
  [0.43398112 0.48232275 0.6918219 ]
  [0.432509   0.35505384 0.75521255]
  [0.51346993 0.4253895  0.886561  ]
  [0.512162   0.40669712 0.8595267 ]
  [0.57846683 0.43072477 0.77047396]
  [0.5761434  0.40075824 0.9070515 ]
  [0.63411194 0.43552446 0.8792    ]
  [0.62837875 0.39777586 0.82669604]]

 [[0.40426975 0.91532415 0.6491448 ]
  [0.39974868 0.9189518  0.55095184]
  [0.4000573  0.9126563  0.5378505 ]
  [0.4065439  0.9228134  0.5598454 ]
  [0.40683457 0.9092725  0.6516491 ]
  [0.4310884  0.9331403  0.8966761 ]
  [0.43237743 0.8994069  0.867067  ]
  [0.42849872 0.9606929  0.7539038 ]
  [0.43583542 0.87535536 0.6370582 ]
  [0.42099163 0.98143    0.75222504]

[[[0.4043699  0.4150403  0.64337564]
  [0.39994013 0.41867548 0.548208  ]
  [0.40007567 0.4124814  0.58230674]
  [0.40658516 0.42236063 0.5880614 ]
  [0.40638214 0.40905023 0.62520486]
  [0.4333826  0.43167052 0.8559029 ]
  [0.43404138 0.3993264  0.8556754 ]
  [0.4341262  0.45581076 0.76819897]
  [0.4370246  0.3756239  0.67642504]
  [0.4328683  0.48193714 0.72639495]
  [0.43067563 0.35462227 0.79390836]
  [0.51349235 0.42519546 0.88424915]
  [0.51213324 0.40596056 0.8788808 ]
  [0.578262   0.43066916 0.77535015]
  [0.5753635  0.4006637  0.90475637]
  [0.63370967 0.4354507  0.87083966]
  [0.62817514 0.39779067 0.83031756]]

 [[0.4044758  0.08360615 0.6426553 ]
  [0.40051946 0.08664296 0.522686  ]
  [0.40056357 0.08093717 0.54536587]
  [0.40639943 0.09049597 0.58390033]
  [0.40628788 0.07734919 0.63685066]
  [0.43276882 0.1017822  0.884206  ]
  [0.43188223 0.06840909 0.8558573 ]
  [0.4278649  0.12853162 0.7787842 ]
  [0.433961   0.04181717 0.7878361 ]
  [0.42204177 0.14575966 0.76118577]

[[[0.40453562 0.41521192 0.6613144 ]
  [0.3996361  0.41895467 0.5702114 ]
  [0.39994916 0.4125733  0.58478886]
  [0.40627962 0.42194983 0.6044388 ]
  [0.40654677 0.40901786 0.65331435]
  [0.4334277  0.4319726  0.87039554]
  [0.43422794 0.39906728 0.86564344]
  [0.4336375  0.45723638 0.7902285 ]
  [0.4368057  0.37526056 0.6899536 ]
  [0.43189353 0.48293948 0.6674902 ]
  [0.431061   0.3542447  0.8011562 ]
  [0.51411206 0.42553887 0.8986689 ]
  [0.51215905 0.40618324 0.8739647 ]
  [0.5787988  0.4307668  0.77782816]
  [0.5751169  0.40110204 0.90885645]
  [0.63387215 0.43552828 0.8710342 ]
  [0.62844324 0.3977488  0.84572995]]

 [[0.40457365 0.08348214 0.6360838 ]
  [0.40061456 0.08655418 0.5436658 ]
  [0.4004844  0.08083503 0.5566474 ]
  [0.4063003  0.09034078 0.5885927 ]
  [0.40604803 0.07736223 0.6351642 ]
  [0.43241084 0.10178621 0.88725007]
  [0.43154365 0.06843694 0.85803485]
  [0.42803162 0.12920836 0.7914498 ]
  [0.43335414 0.04190614 0.78905845]
  [0.42179033 0.14630306 0.75538564]

[[[0.40428084 0.41487977 0.6749833 ]
  [0.39950258 0.41863328 0.5160613 ]
  [0.39979368 0.41238794 0.606884  ]
  [0.40599096 0.42167518 0.63009214]
  [0.40635177 0.4090161  0.6604405 ]
  [0.4325503  0.43198624 0.8807427 ]
  [0.4345727  0.39895603 0.8617013 ]
  [0.43299994 0.45711803 0.80286133]
  [0.43762326 0.37561995 0.6665476 ]
  [0.43141103 0.48294654 0.68437344]
  [0.4311486  0.35459533 0.7954246 ]
  [0.514332   0.42538854 0.8951219 ]
  [0.51251245 0.40609953 0.8808744 ]
  [0.5787377  0.43061802 0.7601381 ]
  [0.5757563  0.40087914 0.90886533]
  [0.63388604 0.4354972  0.87110513]
  [0.6284561  0.3977032  0.8484279 ]]

 [[0.40584737 0.91585964 0.5539125 ]
  [0.40118533 0.91929334 0.5923921 ]
  [0.40159172 0.9131078  0.60749   ]
  [0.40732378 0.923082   0.5941325 ]
  [0.40721375 0.90995187 0.6688592 ]
  [0.43148383 0.9335143  0.8936388 ]
  [0.4329171  0.8996835  0.833998  ]
  [0.42865008 0.960137   0.77686197]
  [0.4349264  0.8742723  0.733502  ]
  [0.42112297 0.9816081  0.7375016 ]

[[[0.40566465 0.915792   0.5640949 ]
  [0.40101013 0.91927147 0.58913034]
  [0.40139914 0.9130769  0.5959987 ]
  [0.40720448 0.9230585  0.5896499 ]
  [0.4068919  0.90977955 0.66348726]
  [0.4312771  0.93354434 0.8950286 ]
  [0.43273172 0.89966387 0.8399383 ]
  [0.42866474 0.9609705  0.7795711 ]
  [0.4346301  0.8739954  0.73492223]
  [0.4216554  0.98261374 0.7127861 ]
  [0.4295985  0.85487026 0.7815231 ]
  [0.5128188  0.9265469  0.9058147 ]
  [0.51143837 0.9070794  0.8699253 ]
  [0.5784625  0.9313653  0.87791723]
  [0.57273877 0.9036016  0.86227524]
  [0.6330297  0.93469137 0.90437186]
  [0.6284433  0.8975264  0.8168246 ]]

 [[0.40424368 0.41470367 0.67302066]
  [0.4001906  0.41783515 0.53443927]
  [0.39973864 0.41225168 0.61874443]
  [0.40592802 0.42161724 0.6351195 ]
  [0.40621006 0.40893552 0.6654563 ]
  [0.43249807 0.4318463  0.8778511 ]
  [0.4343272  0.39879102 0.86579466]
  [0.4331209  0.4569946  0.80303425]
  [0.43748558 0.37560573 0.67464644]
  [0.43135592 0.4829235  0.6872466 ]

[[[0.4054688  0.9157082  0.58507323]
  [0.4009206  0.9191619  0.5774077 ]
  [0.4012863  0.9129862  0.58133954]
  [0.4073124  0.92289764 0.5951653 ]
  [0.40697557 0.9096937  0.6635546 ]
  [0.43120378 0.9334853  0.8959758 ]
  [0.43273994 0.8995013  0.8510834 ]
  [0.42916223 0.9607994  0.78780884]
  [0.4349488  0.8737736  0.7275403 ]
  [0.42128533 0.9821973  0.7064603 ]
  [0.4301456  0.85497206 0.77583426]
  [0.51262915 0.9264904  0.9032034 ]
  [0.5112782  0.9069935  0.8696298 ]
  [0.57866734 0.93138564 0.8788427 ]
  [0.5726968  0.90364045 0.86961377]
  [0.63291335 0.9348383  0.9051054 ]
  [0.62842387 0.8974984  0.81854695]]

 [[0.4041636  0.41490975 0.6857431 ]
  [0.39938647 0.41861826 0.50148493]
  [0.39958712 0.41231927 0.5892885 ]
  [0.40594327 0.42161846 0.63340414]
  [0.40622967 0.40865508 0.662231  ]
  [0.4325331  0.4316078  0.8797524 ]
  [0.4345406  0.39880142 0.8687104 ]
  [0.4328478  0.45652348 0.79549384]
  [0.43605015 0.37425467 0.72805494]
  [0.43118197 0.48534057 0.66935945]

[[[0.40592957 0.9159727  0.5496157 ]
  [0.40135568 0.9194891  0.61920214]
  [0.40150687 0.91315585 0.6236981 ]
  [0.4075337  0.9229557  0.60428   ]
  [0.40713346 0.9094688  0.67017597]
  [0.43146664 0.93339646 0.89765155]
  [0.43300086 0.89938325 0.8479707 ]
  [0.42986512 0.96090746 0.7707823 ]
  [0.4346118  0.8732895  0.72149736]
  [0.4218418  0.983308   0.7004964 ]
  [0.42938513 0.85488623 0.7834382 ]
  [0.5122055  0.92648476 0.8979859 ]
  [0.5109097  0.90698624 0.8579641 ]
  [0.5779049  0.9312996  0.8712493 ]
  [0.5727764  0.9036118  0.8673084 ]
  [0.63213646 0.9347663  0.90787345]
  [0.62841296 0.8973233  0.81668097]]

 [[0.40390915 0.5822558  0.6302995 ]
  [0.39992464 0.5855183  0.64759505]
  [0.40028846 0.57962906 0.69578755]
  [0.4061936  0.5888458  0.6041348 ]
  [0.40655333 0.575719   0.57919776]
  [0.43318987 0.59871835 0.8296746 ]
  [0.43251503 0.5654552  0.88600975]
  [0.43297023 0.6285006  0.8159405 ]
  [0.43306407 0.5429577  0.69123465]
  [0.43234164 0.64763707 0.7609783 ]

[[[0.4055496  0.91596216 0.55841047]
  [0.40124744 0.9194791  0.62224287]
  [0.40131745 0.91318744 0.61924267]
  [0.40775567 0.9230124  0.603333  ]
  [0.40725493 0.90962124 0.669305  ]
  [0.43177223 0.93335706 0.8934713 ]
  [0.4332393  0.8993371  0.8386494 ]
  [0.42994624 0.96068573 0.7708269 ]
  [0.4348622  0.87379473 0.7177931 ]
  [0.42176923 0.98232186 0.7025813 ]
  [0.4295975  0.85505575 0.7934658 ]
  [0.512643   0.9263377  0.90113366]
  [0.51120514 0.9069557  0.86264545]
  [0.57875013 0.9312472  0.8713895 ]
  [0.5735458  0.9034359  0.8868734 ]
  [0.63281715 0.93479836 0.9037067 ]
  [0.6284638  0.897342   0.8192834 ]]

 [[0.40238672 0.41477284 0.72020483]
  [0.39874715 0.41796476 0.46708107]
  [0.39838824 0.41230628 0.537092  ]
  [0.40572572 0.42133567 0.649994  ]
  [0.40578243 0.4089013  0.6905329 ]
  [0.43173718 0.43165317 0.8800811 ]
  [0.43457302 0.3986689  0.86267316]
  [0.43366325 0.45749268 0.7722652 ]
  [0.4362373  0.37376878 0.77035403]
  [0.43205196 0.48697248 0.65082   ]

[[[0.40578946 0.91603404 0.5498016 ]
  [0.4014958  0.91951084 0.63617766]
  [0.40164346 0.91326714 0.64138025]
  [0.40825078 0.92282814 0.63587785]
  [0.4077762  0.9096983  0.7026428 ]
  [0.4320657  0.93308735 0.8855263 ]
  [0.43315563 0.8994778  0.84079605]
  [0.42944798 0.9602911  0.77500397]
  [0.4341107  0.87334555 0.7196366 ]
  [0.4206912  0.9818187  0.7386222 ]
  [0.4299129  0.8547474  0.7872668 ]
  [0.5121367  0.92638063 0.89898527]
  [0.51088446 0.9068599  0.8529744 ]
  [0.5786188  0.9312269  0.86467856]
  [0.57297176 0.9032607  0.8781263 ]
  [0.63269126 0.9348113  0.90571755]
  [0.6284377  0.8974571  0.8250195 ]]

 [[0.40353125 0.5817506  0.5741724 ]
  [0.39944538 0.5850202  0.661695  ]
  [0.39993784 0.57927364 0.73034   ]
  [0.40560886 0.5884301  0.6002545 ]
  [0.4061349  0.57586735 0.60255075]
  [0.43289912 0.59855545 0.82446396]
  [0.43212807 0.5655586  0.8935844 ]
  [0.43434867 0.6285019  0.8089256 ]
  [0.43326855 0.54148316 0.7352685 ]
  [0.43286353 0.64884686 0.75549483]

[[[0.40583837 0.9160592  0.5484438 ]
  [0.40150136 0.91953117 0.6423201 ]
  [0.4016423  0.9132704  0.6508107 ]
  [0.40828216 0.9228676  0.6386281 ]
  [0.40780756 0.9096851  0.7012959 ]
  [0.4323092  0.93315136 0.884786  ]
  [0.43325883 0.8995086  0.8377665 ]
  [0.42952764 0.96044225 0.7825581 ]
  [0.4342686  0.87333536 0.7251275 ]
  [0.4209422  0.9819789  0.72933525]
  [0.42980868 0.85472435 0.7938143 ]
  [0.51216954 0.9263299  0.8990761 ]
  [0.5108339  0.9067405  0.8491259 ]
  [0.5786488  0.931193   0.8591078 ]
  [0.572539   0.90347654 0.8730245 ]
  [0.63226014 0.93477774 0.9068596 ]
  [0.6284374  0.897404   0.8284875 ]]

 [[0.40380585 0.58180356 0.57051164]
  [0.3997118  0.58506095 0.67058957]
  [0.40022463 0.57927    0.7281934 ]
  [0.40581453 0.58850414 0.60438985]
  [0.40639257 0.5758981  0.5970903 ]
  [0.43283975 0.59862274 0.8213469 ]
  [0.432032   0.5656714  0.8932017 ]
  [0.43394417 0.62861013 0.80608433]
  [0.43335462 0.5419145  0.7465924 ]
  [0.43200392 0.6491618  0.7380337 ]

[[[0.40365505 0.58180183 0.57800657]
  [0.39961407 0.58513254 0.6719138 ]
  [0.40003884 0.5793054  0.7128985 ]
  [0.405758   0.58877707 0.619655  ]
  [0.40618676 0.5759968  0.60563976]
  [0.43220732 0.59880716 0.8314666 ]
  [0.4318367  0.56559545 0.8940814 ]
  [0.43208563 0.62871665 0.78845406]
  [0.4334614  0.5413081  0.7648551 ]
  [0.43189988 0.6495347  0.7343264 ]
  [0.4326596  0.5183067  0.8287186 ]
  [0.5168504  0.59180486 0.89020246]
  [0.51353925 0.5730303  0.925597  ]
  [0.5799905  0.5979505  0.8665397 ]
  [0.57729435 0.56717026 0.87370205]
  [0.63316846 0.6017992  0.8978342 ]
  [0.62973714 0.56367743 0.8988229 ]]

 [[0.4073051  0.91635746 0.5725184 ]
  [0.4021808  0.91978306 0.67744434]
  [0.4021636  0.91336745 0.67459697]
  [0.40837973 0.92309153 0.6405068 ]
  [0.4079637  0.9097131  0.7106991 ]
  [0.4320973  0.9331132  0.886637  ]
  [0.4330439  0.8992503  0.8508274 ]
  [0.4289599  0.9604818  0.77132845]
  [0.43503475 0.8739263  0.6898962 ]
  [0.42110628 0.9821849  0.7215595 ]

[[[0.40485013 0.2503396  0.4921477 ]
  [0.40061355 0.25366655 0.7034426 ]
  [0.40089512 0.24774423 0.7171978 ]
  [0.40628052 0.25672624 0.5827015 ]
  [0.40627217 0.24423662 0.602582  ]
  [0.43210745 0.26638165 0.8893289 ]
  [0.43154508 0.23362255 0.9079567 ]
  [0.4345424  0.29100385 0.6744387 ]
  [0.4375263  0.21156804 0.5545009 ]
  [0.43620163 0.31501064 0.6673427 ]
  [0.43853003 0.18922351 0.75183594]
  [0.51225495 0.2583356  0.9026218 ]
  [0.5100632  0.2401386  0.88128954]
  [0.5745782  0.26420996 0.8698291 ]
  [0.5745703  0.23503776 0.89730126]
  [0.63156843 0.26863387 0.882883  ]
  [0.6299449  0.23115242 0.84182537]]

 [[0.4020793  0.41512594 0.7350963 ]
  [0.39787897 0.4185784  0.4611324 ]
  [0.39818084 0.41240832 0.47987288]
  [0.4049356  0.42133757 0.68230593]
  [0.4057935  0.40858918 0.69739366]
  [0.43105432 0.43103027 0.86486554]
  [0.4336999  0.39881027 0.87677944]
  [0.4316336  0.4566389  0.7725033 ]
  [0.4360336  0.37512717 0.56320065]
  [0.4319434  0.4845875  0.7174049 ]

[[[0.4023666  0.4151961  0.73753214]
  [0.39812398 0.41871414 0.47397047]
  [0.39840853 0.41246518 0.48016846]
  [0.40516883 0.42156482 0.66608006]
  [0.40596992 0.40862843 0.6836036 ]
  [0.43118244 0.43131447 0.8730834 ]
  [0.4336822  0.398802   0.87678486]
  [0.43188593 0.45745617 0.7892189 ]
  [0.4356879  0.37654498 0.56869537]
  [0.43202478 0.48608693 0.713488  ]
  [0.43259162 0.3531781  0.7858007 ]
  [0.5152669  0.42517462 0.8903897 ]
  [0.51314795 0.4061346  0.8644239 ]
  [0.5802765  0.4309759  0.79017866]
  [0.57730734 0.4011747  0.9142401 ]
  [0.6356284  0.4353759  0.87506974]
  [0.6296357  0.397854   0.81694686]]

 [[0.40431437 0.25037736 0.5177198 ]
  [0.40042257 0.25373697 0.7051179 ]
  [0.40038514 0.24788187 0.7311924 ]
  [0.40681145 0.25667554 0.5751676 ]
  [0.406263   0.2442011  0.6001285 ]
  [0.43201363 0.26619923 0.8924733 ]
  [0.43209597 0.23365875 0.90803206]
  [0.43238652 0.29018378 0.66774875]
  [0.43990633 0.21067153 0.6448255 ]
  [0.43321365 0.3138688  0.7307262 ]

[[[0.40295133 0.41560578 0.7424329 ]
  [0.3982819  0.41912523 0.52148664]
  [0.39863294 0.41276088 0.4574507 ]
  [0.4051953  0.42200398 0.6434916 ]
  [0.40611947 0.40872929 0.68494046]
  [0.431495   0.43191037 0.88819075]
  [0.4334502  0.3989559  0.87379223]
  [0.43189234 0.45873713 0.79755807]
  [0.43521696 0.37648508 0.56278384]
  [0.4317357  0.48748094 0.72012746]
  [0.43220395 0.35311145 0.7986832 ]
  [0.51515305 0.42527825 0.8932238 ]
  [0.5128603  0.4061391  0.8696228 ]
  [0.5802745  0.43103462 0.79348034]
  [0.577366   0.40112907 0.9160416 ]
  [0.6357026  0.4353819  0.8749632 ]
  [0.6297512  0.3978389  0.82223886]]

 [[0.4045093  0.91500026 0.61558574]
  [0.40043315 0.91860527 0.5392177 ]
  [0.400335   0.91245097 0.58562165]
  [0.4069211  0.922667   0.5674735 ]
  [0.4068924  0.9092499  0.63562757]
  [0.43130106 0.93282    0.8819532 ]
  [0.43348843 0.8990397  0.8554691 ]
  [0.42920932 0.9596526  0.7364263 ]
  [0.4350195  0.8766802  0.58952993]
  [0.42153883 0.9779784  0.7953797 ]

[[[0.40282828 0.4155588  0.7528335 ]
  [0.3981864  0.41913706 0.5212419 ]
  [0.39841342 0.41281843 0.4691366 ]
  [0.40507063 0.42210898 0.6416517 ]
  [0.40577802 0.40893778 0.69637066]
  [0.43135414 0.43188873 0.8923939 ]
  [0.43313158 0.39915326 0.88092995]
  [0.43168914 0.45799708 0.7840623 ]
  [0.4340844  0.37656054 0.51916045]
  [0.43204492 0.48657176 0.7269241 ]
  [0.43117625 0.3537416  0.7869742 ]
  [0.5150115  0.4252337  0.8906978 ]
  [0.512784   0.40619093 0.8667684 ]
  [0.58031493 0.4309833  0.7833764 ]
  [0.57736176 0.4011034  0.91821146]
  [0.63581926 0.43537685 0.8728458 ]
  [0.62977177 0.39784208 0.8236271 ]]

 [[0.40485904 0.9152852  0.6187754 ]
  [0.40056235 0.91875184 0.55902445]
  [0.40066585 0.91254395 0.55314857]
  [0.40694243 0.92249405 0.5765356 ]
  [0.40747052 0.9090433  0.6608972 ]
  [0.43163615 0.93245965 0.87682503]
  [0.43358836 0.8990079  0.8610395 ]
  [0.42898214 0.95941335 0.7465189 ]
  [0.43435913 0.8771885  0.561802  ]
  [0.42113292 0.9777302  0.789487  ]

[[[0.40252993 0.41532135 0.76385194]
  [0.39787287 0.4190311  0.4970319 ]
  [0.39807564 0.41268206 0.48241144]
  [0.4048054  0.42217237 0.6494992 ]
  [0.40535003 0.40900835 0.7132226 ]
  [0.43130237 0.43190175 0.8875761 ]
  [0.43278712 0.3992241  0.88347363]
  [0.43170306 0.4579687  0.79072857]
  [0.43466493 0.3750315  0.52283114]
  [0.4321669  0.48650262 0.714079  ]
  [0.43116006 0.35368493 0.78682333]
  [0.5152068  0.42527086 0.89280367]
  [0.5128982  0.40620866 0.86414295]
  [0.5802539  0.43090746 0.776048  ]
  [0.57697344 0.4012719  0.9157021 ]
  [0.63564396 0.43537936 0.87342715]
  [0.629569   0.39784947 0.82477236]]

 [[0.40505618 0.9156229  0.6328172 ]
  [0.40040177 0.9189947  0.5915082 ]
  [0.40077263 0.912665   0.5353325 ]
  [0.40674838 0.9226179  0.56283534]
  [0.40754724 0.90883875 0.65941614]
  [0.43150353 0.9327016  0.8861905 ]
  [0.43315363 0.8989216  0.8744795 ]
  [0.4288057  0.95960647 0.75413567]
  [0.43450806 0.8755515  0.5412025 ]
  [0.42075786 0.9779542  0.78371984]

[[[0.40270436 0.4151462  0.759771  ]
  [0.39796826 0.41889665 0.48413298]
  [0.3983427  0.41253635 0.5081702 ]
  [0.40491205 0.42219815 0.646607  ]
  [0.40561494 0.4090545  0.7021047 ]
  [0.43135655 0.4319543  0.891925  ]
  [0.4331633  0.399292   0.8814364 ]
  [0.43188286 0.4577941  0.7858505 ]
  [0.43517137 0.3746712  0.5289113 ]
  [0.43227744 0.48590446 0.73098165]
  [0.43140352 0.3533785  0.7901905 ]
  [0.5151813  0.42520815 0.89092255]
  [0.5129285  0.40624505 0.8611604 ]
  [0.580083   0.43084747 0.77089876]
  [0.5763457  0.40129372 0.9140298 ]
  [0.6354518  0.43533784 0.8717248 ]
  [0.62945753 0.39778626 0.82350934]]

 [[0.40466094 0.91555065 0.66501904]
  [0.3999583  0.9189296  0.56428653]
  [0.40040976 0.9125538  0.51835555]
  [0.40639386 0.92228043 0.5602659 ]
  [0.40717548 0.9086482  0.6482664 ]
  [0.43124017 0.93275017 0.89131427]
  [0.43346983 0.89890665 0.87359047]
  [0.42855775 0.95928854 0.755521  ]
  [0.43506503 0.87607014 0.54158926]
  [0.42077184 0.9777374  0.78157383]

[[[0.4045323  0.91553557 0.6736419 ]
  [0.3998272  0.9189376  0.5636811 ]
  [0.4003025  0.91256255 0.5089349 ]
  [0.40637836 0.9225969  0.55869323]
  [0.4071554  0.9085957  0.65160143]
  [0.43118024 0.93290484 0.889901  ]
  [0.43388197 0.8988206  0.87171984]
  [0.42906618 0.9593919  0.760561  ]
  [0.43560347 0.8761172  0.53432584]
  [0.42064792 0.9786483  0.7769273 ]
  [0.43430263 0.8537944  0.7541685 ]
  [0.5133945  0.9259929  0.8984718 ]
  [0.5119039  0.90624446 0.8673727 ]
  [0.5786054  0.9312603  0.8483669 ]
  [0.57463616 0.90274525 0.8848273 ]
  [0.6321641  0.9348815  0.90087056]
  [0.628577   0.8975344  0.8140383 ]]

 [[0.4028078  0.41499576 0.75857717]
  [0.39808583 0.4187828  0.47136807]
  [0.39843607 0.41244528 0.5275115 ]
  [0.40498877 0.422142   0.64866817]
  [0.4057116  0.40901405 0.70052433]
  [0.43138492 0.4319651  0.8896112 ]
  [0.43319833 0.39918643 0.8896327 ]
  [0.43197474 0.45773482 0.7848087 ]
  [0.43473428 0.37622476 0.5675022 ]
  [0.43229836 0.48583937 0.73301727]

[[[0.40419465 0.91549844 0.6924628 ]
  [0.39946413 0.9189976  0.5644586 ]
  [0.3998015  0.91261226 0.48562503]
  [0.40609586 0.92245877 0.5718469 ]
  [0.40706557 0.90872157 0.6303183 ]
  [0.43055212 0.93310827 0.89111584]
  [0.43317652 0.89877284 0.8781288 ]
  [0.42754194 0.9601426  0.74421513]
  [0.43522584 0.87697166 0.5679386 ]
  [0.41850793 0.9810013  0.7391282 ]
  [0.43315017 0.8541996  0.75615436]
  [0.5132539  0.9259281  0.89779377]
  [0.51181054 0.9061349  0.86876523]
  [0.578485   0.9314036  0.8495397 ]
  [0.5745932  0.90287495 0.8900886 ]
  [0.6320872  0.93482095 0.9006139 ]
  [0.6287317  0.89743245 0.8165569 ]]

 [[0.4025455  0.4155042  0.75916165]
  [0.39785108 0.4191331  0.50882727]
  [0.3982428  0.41281015 0.46932676]
  [0.40475917 0.42217684 0.6496942 ]
  [0.40561384 0.40907255 0.70299715]
  [0.43149135 0.43188754 0.8901221 ]
  [0.43321127 0.39945546 0.8782377 ]
  [0.4319358  0.4576419  0.77829146]
  [0.4349004  0.37622023 0.5652733 ]
  [0.43225425 0.48504874 0.72986436]

[[[0.402633   0.41552517 0.752793  ]
  [0.39798722 0.41912937 0.51067   ]
  [0.39832562 0.41286492 0.46705347]
  [0.404828   0.42213115 0.6489136 ]
  [0.40561816 0.4091414  0.70309526]
  [0.4315849  0.43197584 0.8910206 ]
  [0.43318135 0.39953184 0.8768994 ]
  [0.43230724 0.4578955  0.7850832 ]
  [0.43492934 0.37601224 0.57939726]
  [0.43244296 0.4860572  0.72847646]
  [0.43162268 0.35320136 0.7805451 ]
  [0.51474553 0.4254302  0.8955065 ]
  [0.5123272  0.40630937 0.8586108 ]
  [0.5798237  0.43082175 0.7779831 ]
  [0.5753932  0.40147972 0.9149149 ]
  [0.63507706 0.43528333 0.8781778 ]
  [0.6298204  0.39792272 0.82518464]]

 [[0.40397948 0.9156453  0.6998627 ]
  [0.39923495 0.91903514 0.57647574]
  [0.4001132  0.9128503  0.45436314]
  [0.40490526 0.92265797 0.5929472 ]
  [0.40569255 0.9098878  0.6413294 ]
  [0.42776895 0.93249863 0.8400643 ]
  [0.42794585 0.90032214 0.7844348 ]
  [0.40844554 0.9511992  0.6861217 ]
  [0.41132402 0.88454324 0.66748255]
  [0.38612506 0.96798354 0.7464528 ]

[[[0.4026161  0.41565272 0.7646691 ]
  [0.39780658 0.4192898  0.53103244]
  [0.3976701  0.412741   0.46226722]
  [0.40472    0.422333   0.6430686 ]
  [0.40547436 0.40914807 0.7081136 ]
  [0.43144175 0.43202645 0.89725167]
  [0.4330451  0.39967406 0.8786885 ]
  [0.43209535 0.45812854 0.78516227]
  [0.4342861  0.37604323 0.5373708 ]
  [0.43233085 0.48623252 0.723229  ]
  [0.4316029  0.35362387 0.7649404 ]
  [0.5143473  0.42545953 0.8942263 ]
  [0.51202106 0.4063034  0.85663503]
  [0.5798098  0.43092948 0.79041594]
  [0.5752194  0.40152025 0.91446793]
  [0.6350284  0.43530628 0.8818897 ]
  [0.62959176 0.39773783 0.8241108 ]]

 [[0.4037218  0.5827898  0.67246175]
  [0.39955136 0.5858912  0.5758649 ]
  [0.39989755 0.5801762  0.61855155]
  [0.40571553 0.5895947  0.6407122 ]
  [0.4064361  0.5764904  0.6190613 ]
  [0.43307802 0.6000275  0.85049653]
  [0.43165717 0.5661543  0.8947706 ]
  [0.43205553 0.6276468  0.7358969 ]
  [0.4337201  0.54073894 0.7524129 ]
  [0.43320304 0.64848286 0.71489465]

# TensorFlow Lite

In [6]:
### Optional if you are using a GPU
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)

### Load Model
interpreter  = tf.lite.Interpreter(model_path = '../../model/movenet/lite-model_movenet_multipose_lightning_tflite_float16_1.tflite')
interpreter.allocate_tensors() #have to do when working on tflite model 

### Load Video
video_path = '../../data/videos/'
sampleVideo = video_path + 'sampleVideo.mp4'
basicFour = video_path + 'basic_four.mp4'
basicTwo = video_path + 'basic_two.mp4'
swingDiff = video_path + 'swing_diff.mp4'
swingSame = video_path + 'swing_same.mp4'
swingRaw = video_path + 'swingRaw.mp4'
temporalDifficult = video_path + 'temporalDifficultRaw.mp4'
temporalEasy = video_path + 'temporalEasyRaw.mp4'

### Draw EDGES
EDGES = {
    (0, 1): 'm',
    (0, 2): 'c',
    (1, 3): 'm',
    (2, 4): 'c',
    (0, 5): 'm',
    (0, 6): 'c',
    (5, 7): 'm',
    (7, 9): 'm',
    (6, 8): 'c',
    (8, 10): 'c',
    (5, 6): 'y',
    (5, 11): 'm',
    (6, 12): 'c',
    (11, 12): 'y',
    (11, 13): 'm',
    (13, 15): 'm',
    (12, 14): 'c',
    (14, 16): 'c'
}

### Vector List
vectorList = [
    [0,1],
    [0,2],
    [1,3],
    [2,4],
    [3,5],
    [0,6],
    [1,7],
    [6,7],
    [6,8],
    [7,9],
    [8,10],
    [9,10]
]

# Function to loop through each person detected and render
def loop_through_people(frame, keypoints_with_scores, edges, confidence_threshold):
    for person in keypoints_with_scores:
        draw_connections(frame, person, edges, confidence_threshold)
        draw_keypoints(frame, person, confidence_threshold)


def draw_keypoints(frame, keypoints, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    for kp in shaped:
        ky, kx, kp_conf = kp
        if kp_conf > confidence_threshold:
            cv2.circle(frame, (int(kx), int(ky)), 3, (0,255,0), -1)

def draw_connections(frame, keypoints, edges, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    for edge, color in edges.items():
        p1, p2 = edge
        y1, x1, c1 = shaped[p1]
        y2, x2, c2 = shaped[p2]
        
        if (c1 > confidence_threshold) & (c2 > confidence_threshold):      
            cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0,0,255), 2)


###
# Variables for drawing plot in real-time


if __name__ == "__main__":
    ### Variables
    numberOfPeople = 6
#     lamdaVal = 0.885

#     minBPD = 10.0
#     maxBPD = 0.0
    
#     saveNum = 0
    saveBPD = []

    ### Loading Video File
    cap = cv2.VideoCapture(temporalEasy)
    while cap.isOpened():
        ret, frame = cap.read()

        ### Variables for each frame
        BPD = []
        
        # Resize image
        img = frame.copy()
        img = tf.image.resize_with_pad(tf.expand_dims(img, axis=0), 384,640)
        input_img = tf.cast(img, dtype=tf.int32)
        
        # Detection section
        results = movenet(input_img)
        keypoints_with_scores = results['output_0'].numpy()[:,:,:51].reshape((6,17,3))
        keypoints_with_scores = keypoints_with_scores[:numberOfPeople]
        keypoints_only = np.delete(keypoints_with_scores,2,2)
        keypoints_only_body = np.delete(keypoints_only, [0,1,2,3,4], 1)



        # Render keypoints 
        loop_through_people(frame, keypoints_with_scores, EDGES, 0.1)
        # loop_through_people(frame, [keypoints_with_scores[0]], EDGES, 0.1)    # Check for first person.....

        
        cv2.imshow('Movenet Multipose', frame)

        
        if cv2.waitKey(10) & 0xFF==ord('q'):
            break
    
    cap.release()
    cv2.destroyAllWindows()