# Set FPS 3 from webcam

In [1]:
import tensorflow as tf
import tensorflow_hub as hub
import cv2
from matplotlib import pyplot as plt
from matplotlib import animation
import numpy as np
import pandas as pd
import math
import socket
import time
import os

In [14]:
import cv2
import time

cap = cv2.VideoCapture(0)  # Open the default camera
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1980)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 1080)



### Variables for Calculating FPS
initialTime = time.time() # for timeCount
startTime = time.time() # for FPS
startTimeForFrameCount = time.time() # for frame count

# Variable for frame count
frame_count = 1
start_ms = int(round(startTime * 1000))
target_fps = 3  # Desired frames per second


while cap.isOpened():
    ret, frame = cap.read()
    
    currentTime = time.time() # current time
    elapsedTime = currentTime - startTimeForFrameCount
    current_ms = int(round(currentTime * 1000))
    elapsed_ms = current_ms - start_ms
    
    # Calculate Time Count
    timeCount = currentTime - initialTime

    # Calculate the target time interval per frame
    target_interval = 1.0 / target_fps
    

    if elapsedTime >= target_interval:
        frame_count = frame_count + 1
        startTimeForFrameCount = currentTime
        if frame_count > 3:
            frame_count = 1
            
    
    ### Print the frame count and reset the start time
    text_with_frame = "Frame Captured: " + str(frame_count)
    font = cv2.FONT_HERSHEY_SIMPLEX
    location = (50, 50)
    cv2.putText(frame, text_with_frame, location, font, 1, (0, 255, 0), 2)
    
    ### Print the time count
    text_with_frame = "Time Count: " + str(int(timeCount))
    font = cv2.FONT_HERSHEY_SIMPLEX
    location = (50, 100)
    cv2.putText(frame, text_with_frame, location, font, 1, (0, 255, 0), 2)
    
    ### Calculate & Print FPS
    # Calculate FPS
    fps = 1 / (currentTime - startTime)
    startTime = currentTime
    # Save FPS
    fps_str = "FPS : %0.1f" %fps
    # FPS print
    font = cv2.FONT_HERSHEY_SIMPLEX
    location = (50, 150)
    cv2.putText(frame, fps_str, location, font, 1, (0, 255, 0), 2)
    
    # Display the captured frame
    cv2.imshow('Webcam', frame)

    # Exit the loop when the 'q' key is pressed
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the capture and close the window
cap.release()
cv2.destroyAllWindows()

# Compare Cosine Similarity with video call

In [18]:
# Open the CSV file as a DataFrame
csv_path = '../../data/csv/'
csv_name = 'actionPracticeGrandTruth_filtered.csv'
df = pd.read_csv(csv_path + csv_name)
df = df.drop(columns=['t'])

# Convert DataFrame to NumPy array
grandTruth = df.to_numpy()

In [23]:
df

0_y0      0_x0      0_s0      0_y1      0_x1      0_s1      0_y2  \
0   0.397919  0.478782  0.803382  0.389071  0.486113  0.804233  0.389119   
1   0.398620  0.478544  0.795153  0.389770  0.485874  0.805732  0.389161   
2   0.399187  0.478361  0.809267  0.390316  0.485610  0.819930  0.389419   
3   0.398374  0.478326  0.790269  0.389342  0.485614  0.803621  0.389084   
4   0.398492  0.478790  0.815766  0.389452  0.486102  0.793979  0.389157   
..       ...       ...       ...       ...       ...       ...       ...   
89  0.541615  0.465884  0.693647  0.533189  0.474334  0.813375  0.532665   
90  0.532716  0.461327  0.665001  0.526903  0.469705  0.780590  0.524468   
91  0.528495  0.458002  0.765204  0.520903  0.466112  0.756634  0.518444   
92  0.529342  0.457040  0.749341  0.520223  0.465135  0.741121  0.518364   
93  0.528951  0.457365  0.709061  0.520901  0.465800  0.702691  0.518197   

        0_x2      0_s2      0_y3  ...     0_s13     0_y14     0_x14     0_s14  \
0   0.471836  0.867651  0.402675  ...  0.867108  0.754020  0.439783  0.893781   
1   0.471674  0.862219  0.403486  ...  0.864361  0.752994  0.441571  0.895826   
2   0.471593  0.856337  0.403475  ...  0.892152  0.753989  0.440749  0.891932   
3   0.471609  0.853992  0.402676  ...  0.864772  0.752821  0.441182  0.896708   
4   0.472079  0.850470  0.402178  ...  0.867946  0.751797  0.440552  0.897616   
..       ...       ...       ...  ...       ...       ...       ...       ...   
89  0.458980  0.839552  0.552985  ...  0.273905  0.889748  0.429942  0.197782   
90  0.455453  0.726485  0.544641  ...  0.222023  0.905124  0.429405  0.284181   
91  0.451636  0.822853  0.536875  ...  0.262363  0.903631  0.427284  0.239706   
92  0.451071  0.794815  0.533971  ...  0.335133  0.872202  0.430781  0.273293   
93  0.451289  0.773207  0.535876  ...  0.376590  0.870609  0.430321  0.266490   

       0_y15     0_x15     0_s15     0_y16     0_x16     0_s16  
0   0.867669  0.506048  0.902747  0.865302  0.433159  0.859623  
1   0.867099  0.506153  0.897013  0.864045  0.433140  0.857459  
2   0.868544  0.505129  0.898493  0.862588  0.433735  0.890255  
3   0.866799  0.506295  0.898130  0.861904  0.433447  0.885755  
4   0.867389  0.505175  0.903067  0.861573  0.433273  0.883618  
..       ...       ...       ...       ...       ...       ...  
89  0.901825  0.490044  0.855299  0.916161  0.437559  0.248987  
90  0.904716  0.489807  0.849172  0.919068  0.430405  0.181452  
91  0.900077  0.485356  0.877739  0.915347  0.436853  0.350164  
92  0.899288  0.486404  0.883014  0.916259  0.436889  0.350104  
93  0.900505  0.486969  0.890970  0.916783  0.436125  0.361466  

[94 rows x 51 columns]

In [20]:
grandTruth

array([[0.39791855, 0.47878247, 0.8033818 , ..., 0.86530155, 0.43315944,
        0.85962284],
       [0.39861974, 0.4785436 , 0.7951527 , ..., 0.8640453 , 0.43314013,
        0.8574592 ],
       [0.3991871 , 0.47836056, 0.8092666 , ..., 0.86258805, 0.4337351 ,
        0.8902553 ],
       ...,
       [0.5284948 , 0.4580023 , 0.7652043 , ..., 0.9153475 , 0.43685314,
        0.35016426],
       [0.52934164, 0.4570398 , 0.7493414 , ..., 0.9162593 , 0.43688932,
        0.35010365],
       [0.52895117, 0.45736465, 0.7090612 , ..., 0.9167826 , 0.4361249 ,
        0.36146578]])

In [33]:
# Grand Truth normalized
### Detection section
keypoints_with_scores_grandTruth = grandTruth.reshape((1,17,3,94))
#         keypoints_only = np.delete(keypoints_with_scores,2,2)    # remove confidence level
keypoints_only_body_grandTruth = np.delete(keypoints_with_scores_grandTruth, [1,2,3,4], 1)   # raw keypoints value with confidence level

In [34]:
keypoints_only_body_grandTruth.shape

(1, 13, 3, 94)

In [40]:
### Vector List
vectorList = [
    [0,1],
    [0,2],
    [1,2],
    [1,3],
    [2,4],
    [3,5],
    [4,6],
    [1,7],
    [2,8],
    [7,8],
    [7,9],
    [8,10],
    [9,11],
    [10,12]
]

### Calculate normalized vector with average confidence level for each person
norm_vectors_only_body_grandTruth = []
for row in range(keypoints_only_body_grandTruth.shape[-1]):
    tempRow = []
    for person in keypoints_only_body_grandTruth:
        tempPerson = []
        for i in vectorList:
            tempY = person[i[1]][0][row] - person[i[0]][0][row]
            tempX = person[i[1]][1][row] - person[i[0]][1][row]
            tempAverageS = (person[i[1]][2][row] + person[i[0]][2][row])/2
            tempVector = np.array([tempX, tempY])
            normalizedTempVector = tempVector / np.linalg.norm(tempVector)
            tempPerson.append([normalizedTempVector[0], normalizedTempVector[1], tempAverageS])
        tempRow.append(tempPerson)
    norm_vectors_only_body_grandTruth.append(tempRow)

norm_vectors_only_body_grandTruth = np.array(norm_vectors_only_body_grandTruth)
norm_vectors_only_body_grandTruth.reshape(1,len(vectorList),3,keypoints_only_body_grandTruth.shape[-1])

array([[[[-0.23759937,  0.97136324,  0.7619678 , ..., -0.95682797,
           0.44982896, -0.29222307],
         [ 0.95635018,  0.44702258, -0.79550342, ...,  0.51219821,
           0.68345467, -0.72999295],
         [ 0.39901659,  0.98601581,  0.16665183, ..., -0.50266968,
          -0.86447856,  0.49430115]],

        [[-0.24436106, -0.96968432,  0.6176693 , ...,  0.97934675,
           0.45724286,  0.42815389],
         [ 0.90370584,  0.45495414, -0.06596103, ...,  0.47060701,
          -0.94788301,  0.31861859],
         [ 0.42919306,  0.90606033,  0.42314853, ...,  0.92989088,
           0.3678355 ,  0.61284183]],

        [[-0.93396224,  0.3573717 ,  0.3975549 , ...,  0.88161021,
           0.64770832, -0.16738696],
         [ 0.98589128,  0.79685002,  0.9772054 , ...,  0.40058746,
           0.94624502, -0.32345072],
         [ 0.48587033,  0.56664963, -0.82395885, ...,  0.41513641,
          -0.90975918,  0.45005328]],

        ...,

        [[-0.99415018, -0.10800653,  0.44615

In [42]:
norm_vectors_only_body_grandTruth.shape

(94, 1, 14, 3)

In [67]:
from PIL import Image

### Optional if you are using a GPU
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)

### Load Model
model = hub.load('https://tfhub.dev/google/movenet/multipose/lightning/1')
movenet = model.signatures['serving_default']

# ### Load Video
# video_path = '../../data/videos/'
# actionPractice = video_path + 'actionPracticeWhite.mp4'

### Set the size of Load Image
im_height = 1080
im_width = 1980

# Load Pose_Hand_Images with Array
concert_list = []
path = '../../data/material/concert/'
fileType = '.png'
fileList = os.listdir(path)
fileList.sort()
for i in range(0, 5):
    original = Image.open(path + 'level' + str(i) + fileType)
    concert_list.append(original.resize((im_width, im_height), Image.ANTIALIAS))


### Draw NEW_EDGES
NEW_EDGES = {
    (0, 6): 'm',
    (0, 5): 'm',
    (5, 7): 'm',
    (7, 9): 'm',
    (6, 8): 'c',
    (8, 10): 'c',
    (5, 6): 'y',
    (5, 11): 'm',
    (6, 12): 'c',
    (11, 12): 'y',
    (11, 13): 'm',
    (13, 15): 'm',
    (12, 14): 'c',
    (14, 16): 'c'
}

### Vector List
vectorList = [
    [0,1],
    [0,2],
    [1,2],
    [1,3],
    [2,4],
    [3,5],
    [4,6],
    [1,7],
    [2,8],
    [7,8],
    [7,9],
    [8,10],
    [9,11],
    [10,12]
]


# Function to loop through each person detected and render
def loop_through_people(frame, keypoints_with_scores, edges, confidence_threshold, cosineDistance_with_confidence):
    for idx, person in enumerate(keypoints_with_scores):
        draw_connections(frame, person, edges, confidence_threshold, cosineDistance_with_confidence[idx])
        draw_keypoints(frame, person, confidence_threshold)


def draw_keypoints(frame, keypoints, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    for kp in shaped:
        ky, kx, kp_conf = kp
        if kp_conf > confidence_threshold:
            cv2.circle(frame, (int(kx), int(ky)), 3, (0,255,0), -1)

def draw_connections(frame, keypoints, edges, confidence_threshold, cosineDistance_with_confidence):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
#     color_value_array = []
#     alpha_value_array = []
    for edge, color in edges.items():
        p1, p2 = edge
        y1, x1, c1 = shaped[p1]
        y2, x2, c2 = shaped[p2]
        
#         if (c1 > confidence_threshold) & (c2 > confidence_threshold):      
#             cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0,0,255), 2)
        index = list(edges.keys()).index(edge)
        color_value = np.interp(BPD[index], [0.0,1.0], [0.0,255.0])    # range of BPD with lambda = 1.0: [0,1]
        alpha_value = np.interp(confidence_level[index], [0.0,1.0], [0.0,255.0])    # range of averageConfidence: [0,1]

        
        cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0, 255-color_value, color_value, alpha_value), 10)


###


### Variables for Calculating FPS
initialTime = time.time() # for timeCount
startTime = time.time() # for FPS
startTimeForFrameCount = time.time() # for frame count

# Variable for frame count
frame_count = 1
start_ms = int(round(startTime * 1000))
target_fps = 3  # Desired frames per second

grandTruthCount = 0


# ### Variables for Calculating FPS
# prevTime = time.time() # previous time

if __name__ == "__main__":
    
    ### Variables
    numberOfPeople = 3
    lambdaVal = 1.0
#     lamdaVal = 0.885

#     minBPD = 10.0
#     maxBPD = 0.0
    
#     saveNum = 0
#     saveBPD = []

    ### Loading Video File
    cap = cv2.VideoCapture(0)    ### Change the File Here!!
    # Variables for set the cam size
    cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1980)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 1080)
    
    while cap.isOpened():
        ret, frame = cap.read()
        
        currentTime = time.time() # current time
        elapsedTime = currentTime - startTimeForFrameCount
        current_ms = int(round(currentTime * 1000))
        elapsed_ms = current_ms - start_ms

        # Calculate Time Count
        timeCount = currentTime - initialTime

        # Calculate the target time interval per frame
        target_interval = 1.0 / target_fps


            ### Resize the Concert PNG
            # Resize the PNG image to fit the frame
    #         resized_png = cv2.resize(level_1, (frame.shape[1], frame.shape[0]))


        ### Resize image
        img = frame.copy()
        img = tf.image.resize_with_pad(tf.expand_dims(img, axis=0), 384,640)
        input_img = tf.cast(img, dtype=tf.int32)


        ### Detection section
        results = movenet(input_img)
        keypoints_with_scores = results['output_0'].numpy()[:,:,:51].reshape((6,17,3))
        keypoints_with_scores = keypoints_with_scores[:numberOfPeople]
#         keypoints_with_scores = np.argsort(keypoints_with_scores[:,:,0], axis=-1) # sort with x direction
        # Extract the second row (index 1) from each matrix
        second_rows = keypoints_with_scores[:, 1, :]
        # Sort the indices based on the second row values
        sorted_indices = np.argsort(second_rows[:, 1])
        # Rearrange the original array using the sorted indices
        keypoints_with_scores = keypoints_with_scores[sorted_indices]
        
    #         keypoints_only = np.delete(keypoints_with_scores,2,2)    # remove confidence level
        keypoints_only_body = np.delete(keypoints_with_scores, [1,2,3,4], 1)   # raw keypoints value with confidence level


       ### Calculate normalized vector with average confidence level for each person
        norm_vectors_only_body = []
        for person in keypoints_only_body:
            tempPerson = []
            for i in vectorList:
                tempY = person[i[1]][0] - person[i[0]][0]
                tempX = person[i[1]][1] - person[i[0]][1]
                tempAverageS = (person[i[1]][2] + person[i[0]][2])/2
                tempVector = np.array([tempX, tempY])
                normalizedTempVector = tempVector / np.linalg.norm(tempVector)
                tempPerson.append([normalizedTempVector[0], normalizedTempVector[1], tempAverageS])
            norm_vectors_only_body.append(tempPerson)

        norm_vectors_only_body = np.array(norm_vectors_only_body)
        norm_vectors_only_body.reshape(numberOfPeople,len(vectorList),3)


        ### Calculate cosine distance with average confidence level of two normalized vectors from each person.
        cosineDistance_with_confidence = []

        if elapsedTime >= target_interval:
            frame_count = frame_count + 1
            startTimeForFrameCount = currentTime

            # compare with instructor (norm_vectors_only_body[0])
            for person in range(0, norm_vectors_only_body.shape[0]):
                tempPerson = []
                for row in range(norm_vectors_only_body.shape[1]):
                    tempCosSimilarityRow = []
                    tempInstructorVector = norm_vectors_only_body_grandTruth[grandTruthCount][0,row,:]
                    tempStudentVector = norm_vectors_only_body[person,row,:]

                    cosine_similarity = np.dot(tempInstructorVector[:2], tempStudentVector[:2]) / (np.linalg.norm(tempInstructorVector[:2]) * np.linalg.norm(tempStudentVector[:2]))
                    cosine_distance = math.sqrt(2 * (1 - cosine_similarity))
                    tempAverageConfidence = (tempInstructorVector[2] + tempStudentVector[2]) / 2
                    tempPerson.append([cosine_distance, tempAverageConfidence])
                grandTruthCount += 1
                cosineDistance_with_confidence.append(tempPerson)

            if frame_count > 3:
                frame_count = 1

        cosineDistance_with_confidence = np.array(cosineDistance_with_confidence)
        #cosineDistance_with_confidence.reshape(numberOfPeople-1,2,12)


        # Render keypoints 
        loop_through_people(frame, keypoints_with_scores[1:], NEW_EDGES, 0.1, cosineDistance_with_confidence)    #         loop_through_people(frame, [keypoints_with_scores[0]], EDGES, 0.1)    # Check for first person.....

    #         # Overlay the PNG image on the video
    #         displaySensitivity = 5
    #         level = (np.mean(BPD) * 100) / displaySensitivity
    #         if level > 4:
    #             level = 4
    #         level = 4 - level
    #         pilim = Image.fromarray(frame)
    #         pilim.paste(concert_list[int(level)], box=(0, 0), mask=concert_list[int(level)])
    #         frame = np.array(pilim)

    #         # Print Lambda Value
    #         text_with_lambda = "Lambda Value: " + "{:.2f}".format(lambdaVal)
    #         font = cv2.FONT_HERSHEY_SIMPLEX
    #         location = (50, 50)
    #         cv2.putText(frame, text_with_lambda, location, font, 1, (0, 255, 0), 2)

    #         # Print Average BPD
    #         text_with_averageBPD = "Avg BPD Value: " + "{:.2f}".format(np.mean(BPD) * 100)
    #         font = cv2.FONT_HERSHEY_SIMPLEX
    #         location = (50, 100)
    #         cv2.putText(frame, text_with_averageBPD, location, font, 1, (0, 255, 0), 2)

    #         # Print Level
    #         ratings = ("BAD", "POOR", "FAIR", "GOOD", "EXCELLENT")
    #         text_with_level = "Level: " + ratings[int(level)]
    #         font = cv2.FONT_HERSHEY_SIMPLEX
    #         location = (50, 150)
    #         cv2.putText(frame, text_with_level, location, font, 1, (0, 255, 0), 2)

    #         ### Calculate & Print FPS
    #         # Count Frame
    #         curTime = time.time()	# current time
    #         fps = 1 / (curTime - prevTime)
    #         prevTime = curTime
    #         # Save FPS
    #         fps_str = "FPS : %0.1f" %fps
    #         # FPS print
    #         font = cv2.FONT_HERSHEY_SIMPLEX
    #         location = (50, 200)
    #         cv2.putText(frame, fps_str, location, font, 1, (0, 255, 0), 2)

        ### Print the frame count and reset the start time
        text_with_frame = "Frame Captured: " + str(frame_count)
        font = cv2.FONT_HERSHEY_SIMPLEX
        location = (50, 50)
        cv2.putText(frame, text_with_frame, location, font, 1, (0, 255, 0), 2)

        ### Print the time count
        text_with_frame = "Time Count: " + str(int(timeCount))
        font = cv2.FONT_HERSHEY_SIMPLEX
        location = (50, 100)
        cv2.putText(frame, text_with_frame, location, font, 1, (0, 255, 0), 2)

        ### Calculate & Print FPS
        # Calculate FPS
        fps = 1 / (currentTime - startTime)
        startTime = currentTime
        # Save FPS
        fps_str = "FPS : %0.1f" %fps
        # FPS print
        font = cv2.FONT_HERSHEY_SIMPLEX
        location = (50, 150)
        cv2.putText(frame, fps_str, location, font, 1, (0, 255, 0), 2)

         # Show the frame
        cv2.imshow('Movenet Multipose', frame)

        # when press
        if cv2.waitKey(10) & 0xFF==ord('m'):
            lambdaVal += 0.1
        if cv2.waitKey(10) & 0xFF==ord('n'):
            lambdaVal -= 0.1

        if cv2.waitKey(10) & 0xFF==ord('q'):
            break
    
    cap.release()
    cv2.destroyAllWindows()

C:\Users\LeeSooHwan\AppData\Local\Temp\ipykernel_28608\2834580324.py:28: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  concert_list.append(original.resize((im_width, im_height), Image.ANTIALIAS))


NameError: name 'BPD' is not defined

In [47]:
keypoints_with_scores.shape

(3, 17, 3)

In [52]:
import numpy as np

# Create a sample 3-dimensional array
shape = (3, 17, 3)
array = np.random.randint(0, 100, shape)

# Get indices that would sort the array along the third dimension based on the first value
sorted_indices = np.argsort(array[:, :, 0])

# Apply the sorted indices to the entire array
sorted_array = array[:, sorted_indices, :]

print("Original Array:")
print(array)
print("\nSorted Array based on the first value in the third dimension:")
print(sorted_array)

Original Array:
[[[41  3 81]
  [ 9 77  9]
  [37 62 28]
  [59 37 61]
  [26 84 13]
  [ 8 72 54]
  [ 0  8 97]
  [72  7 43]
  [85 78 34]
  [76 87 96]
  [23 88 75]
  [74 82 74]
  [56 19 39]
  [46 97 97]
  [ 7 75 78]
  [15 77 33]
  [ 2 69  8]]

 [[32 44 30]
  [11 73 46]
  [77 39 92]
  [67 16 37]
  [11 36 88]
  [88 30 89]
  [71 87 92]
  [67 11 88]
  [85  9 17]
  [67 56 18]
  [11 70 65]
  [29 90 92]
  [82 31  6]
  [23 29 49]
  [56  0 19]
  [79 37 11]
  [16 23 65]]

 [[95 83 38]
  [68 94 72]
  [ 3 12 66]
  [59 42 24]
  [20 42 72]
  [63 92 86]
  [ 3 17 74]
  [64 97 73]
  [45 99 47]
  [37 17 49]
  [65  6 13]
  [10 44 88]
  [18 79 64]
  [ 8 27 52]
  [92 56 70]
  [59 17 99]
  [ 0 16 39]]]

Sorted Array based on the first value in the third dimension:
[[[[ 0  8 97]
   [ 2 69  8]
   [ 7 75 78]
   [ 8 72 54]
   [ 9 77  9]
   [15 77 33]
   [23 88 75]
   [26 84 13]
   [37 62 28]
   [41  3 81]
   [46 97 97]
   [56 19 39]
   [59 37 61]
   [72  7 43]
   [74 82 74]
   [76 87 96]
   [85 78 34]]

  [[ 9 77  9

In [55]:
import numpy as np

# Create a sample 3-dimensional array
shape = (3, 17, 3)
array = np.random.randint(0, 100, shape)

# Get indices that would sort the first factor based on the first value of the last factor within each slice
sorted_data = sorted(array, key=lambda x: x[2][0])
# Apply the sorted indices to the entire array


print("Original Array:")
print(array)
print("\nSorted Array by the first value of the last factor within each slice:")
print(sorted_data)

Original Array:
[[[ 4 63 55]
  [28 63 68]
  [90 16  0]
  [18  2 42]
  [16 63  2]
  [90 33 74]
  [54 15 74]
  [66 80 38]
  [28 98 75]
  [95 39 13]
  [56 94 25]
  [84 89 83]
  [75 40 40]
  [72 21 95]
  [77 59 37]
  [88 76  4]
  [81 10 52]]

 [[87  1 69]
  [59 11 28]
  [56 19 83]
  [79 83 16]
  [57 49 47]
  [82 58 99]
  [47 54  1]
  [19 76 63]
  [52 83  4]
  [14 64 30]
  [75 36 42]
  [11 84 74]
  [86 80 30]
  [77 95 58]
  [97 50 35]
  [44 79 66]
  [71 37 50]]

 [[64 21 63]
  [ 3 74 92]
  [30 76  9]
  [23 48 83]
  [41 78 41]
  [40 33 44]
  [52  8 46]
  [96 85 51]
  [69 53 64]
  [72 91 75]
  [56  4 85]
  [95 76 14]
  [54 76 22]
  [77 36 92]
  [29 72 17]
  [49 95 13]
  [71 36 43]]]

Sorted Array by the first value of the last factor within each slice:
[array([[64, 21, 63],
       [ 3, 74, 92],
       [30, 76,  9],
       [23, 48, 83],
       [41, 78, 41],
       [40, 33, 44],
       [52,  8, 46],
       [96, 85, 51],
       [69, 53, 64],
       [72, 91, 75],
       [56,  4, 85],
       [95, 

In [62]:
# Define the original list of matrices
matrices = [
    [[3, 17, 3], [1, 5, 2], [6, 8, 4]],
    [[2, 10, 5], [8, 4, 6], [3, 1, 9]],
    [[7, 12, 8], [4, 15, 7], [9, 3, 10]]
]

# Sort the matrices based on the second row (index 1)
sorted_matrices = sorted(matrices, key=lambda matrix: matrix[0])

# Print the sorted matrices
for matrix in sorted_matrices:
    print(matrix)

[[2, 10, 5], [8, 4, 6], [3, 1, 9]]
[[3, 17, 3], [1, 5, 2], [6, 8, 4]]
[[7, 12, 8], [4, 15, 7], [9, 3, 10]]


In [63]:
import numpy as np

# Define the original list of matrices as NumPy arrays
matrices = [
    np.array([[3, 17, 3], [1, 5, 2], [6, 8, 4]]),
    np.array([[2, 10, 5], [8, 4, 6], [3, 1, 9]]),
    np.array([[7, 12, 8], [4, 15, 7], [9, 3, 10]])
]

# Extract the second row (index 1) from each matrix and sort the indices
sorted_indices = np.argsort([matrix[1] for matrix in matrices])

# Sort the matrices based on the sorted indices
sorted_matrices = [matrices[i] for i in sorted_indices]

# Print the sorted matrices
for matrix in sorted_matrices:
    print(matrix)

TypeError: only integer scalar arrays can be converted to a scalar index

In [65]:
import numpy as np

# Define the original array of matrices
array_of_matrices = np.array([
    [[3, 17, 3], [1, 5, 2], [6, 8, 4]],
    [[2, 10, 5], [8, 4, 6], [3, 1, 9]],
    [[7, 12, 8], [4, 15, 7], [9, 3, 10]]
])

# Extract the second row (index 1) from each matrix
second_rows = array_of_matrices[:, 1, :]

# Sort the indices based on the second row values
sorted_indices = np.argsort(second_rows[:, 1])

# Rearrange the original array using the sorted indices
sorted_array = array_of_matrices[sorted_indices]

# Print the sorted array of matrices
print(sorted_array)

[[[ 2 10  5]
  [ 8  4  6]
  [ 3  1  9]]

 [[ 3 17  3]
  [ 1  5  2]
  [ 6  8  4]]

 [[ 7 12  8]
  [ 4 15  7]
  [ 9  3 10]]]
